package plz

var hessen_map = map[string]PLZ{
	"Aarbergen":                           PLZ{Name: "Aarbergen", Code: []int{65326}},
	"Abtsteinach":                         PLZ{Name: "Abtsteinach", Code: []int{69518}},
	"Ahnatal":                             PLZ{Name: "Ahnatal", Code: []int{34292}},
	"Alheim":                              PLZ{Name: "Alheim", Code: []int{36211}},
	"Allendorf":                           PLZ{Name: "Allendorf", Code: []int{35108, 35469}},
	"Allendorf Battenfeld":                PLZ{Name: "Allendorf Battenfeld", Code: []int{35108}},
	"Allendorf Haine":                     PLZ{Name: "Allendorf Haine", Code: []int{35108}},
	"Allendorf Osterfeld":                 PLZ{Name: "Allendorf Osterfeld", Code: []int{35108}},
	"Allendorf Rennertehausen":            PLZ{Name: "Allendorf Rennertehausen", Code: []int{35108}},
	"Alsbach-Hahnlein":                    PLZ{Name: "Alsbach-Hahnlein", Code: []int{64665}},
	"Alsfeld":                             PLZ{Name: "Alsfeld", Code: []int{36304}},
	"Altenstadt":                          PLZ{Name: "Altenstadt", Code: []int{63674}},
	"Amoneburg":                           PLZ{Name: "Amoneburg", Code: []int{35287}},
	"Angelburg":                           PLZ{Name: "Angelburg", Code: []int{35719}},
	"Antrifttal":                          PLZ{Name: "Antrifttal", Code: []int{36326}},
	"Aslar":                               PLZ{Name: "Aslar", Code: []int{35614}},
	"Babenhausen":                         PLZ{Name: "Babenhausen", Code: []int{64832}},
	"Bad Arolsen":                         PLZ{Name: "Bad Arolsen", Code: []int{34454}},
	"Bad Camberg":                         PLZ{Name: "Bad Camberg", Code: []int{65520}},
	"Bad Emstal":                          PLZ{Name: "Bad Emstal", Code: []int{34308}},
	"Bad Endbach":                         PLZ{Name: "Bad Endbach", Code: []int{35080}},
	"Bad Hersfeld":                        PLZ{Name: "Bad Hersfeld", Code: []int{36251}},
	"Bad Homburg Vor Der Hohe":            PLZ{Name: "Bad Homburg Vor Der Hohe", Code: []int{61348, 61350, 61352}},
	"Bad Karlshafen":                      PLZ{Name: "Bad Karlshafen", Code: []int{34385}},
	"Bad Konig":                           PLZ{Name: "Bad Konig", Code: []int{64732}},
	"Bad Nauheim":                         PLZ{Name: "Bad Nauheim", Code: []int{61231}},
	"Bad Orb":                             PLZ{Name: "Bad Orb", Code: []int{63619}},
	"Bad Salzschlirf":                     PLZ{Name: "Bad Salzschlirf", Code: []int{36364}},
	"Bad Schwalbach":                      PLZ{Name: "Bad Schwalbach", Code: []int{65307}},
	"Bad Soden Am Taunus":                 PLZ{Name: "Bad Soden Am Taunus", Code: []int{65812}},
	"Bad Soden-Salmunster":                PLZ{Name: "Bad Soden-Salmunster", Code: []int{63628}},
	"Bad Sooden-Allendorf":                PLZ{Name: "Bad Sooden-Allendorf", Code: []int{37242}},
	"Bad Vilbel":                          PLZ{Name: "Bad Vilbel", Code: []int{61118}},
	"Bad Wildungen":                       PLZ{Name: "Bad Wildungen", Code: []int{34537}},
	"Bad Zwesten":                         PLZ{Name: "Bad Zwesten", Code: []int{34596}},
	"Battenberg":                          PLZ{Name: "Battenberg", Code: []int{35088}},
	"Baunatal":                            PLZ{Name: "Baunatal", Code: []int{34225}},
	"Bebra":                               PLZ{Name: "Bebra", Code: []int{36179}},
	"Beerfelden":                          PLZ{Name: "Beerfelden", Code: []int{64743}},
	"Bensheim":                            PLZ{Name: "Bensheim", Code: []int{64625}},
	"Berkatal":                            PLZ{Name: "Berkatal", Code: []int{37297}},
	"Beselich":                            PLZ{Name: "Beselich", Code: []int{65614}},
	"Biblis":                              PLZ{Name: "Biblis", Code: []int{68647}},
	"Bickenbach":                          PLZ{Name: "Bickenbach", Code: []int{64404}},
	"Biebergemund":                        PLZ{Name: "Biebergemund", Code: []int{63599}},
	"Biebertal":                           PLZ{Name: "Biebertal", Code: []int{35444}},
	"Biebesheim Am Rhein":                 PLZ{Name: "Biebesheim Am Rhein", Code: []int{64584}},
	"Biedenkopf":                          PLZ{Name: "Biedenkopf", Code: []int{35216}},
	"Birkenau":                            PLZ{Name: "Birkenau", Code: []int{69488}},
	"Birstein":                            PLZ{Name: "Birstein", Code: []int{63633}},
	"Bischoffen":                          PLZ{Name: "Bischoffen", Code: []int{35649}},
	"Bischofsheim":                        PLZ{Name: "Bischofsheim", Code: []int{65474}},
	"Borken":                              PLZ{Name: "Borken", Code: []int{34582}},
	"Brachttal":                           PLZ{Name: "Brachttal", Code: []int{63636}},
	"Braunfels":                           PLZ{Name: "Braunfels", Code: []int{35619}},
	"Braunfels Altenkirchen":              PLZ{Name: "Braunfels Altenkirchen", Code: []int{35619}},
	"Braunfels Bonbaden":                  PLZ{Name: "Braunfels Bonbaden", Code: []int{35619}},
	"Braunfels Braunfels":                 PLZ{Name: "Braunfels Braunfels", Code: []int{35619}},
	"Braunfels Neukirchen":                PLZ{Name: "Braunfels Neukirchen", Code: []int{35619}},
	"Braunfels Philippstein":              PLZ{Name: "Braunfels Philippstein", Code: []int{35619}},
	"Braunfels Tiefenbach":                PLZ{Name: "Braunfels Tiefenbach", Code: []int{35619}},
	"Brechen":                             PLZ{Name: "Brechen", Code: []int{65611}},
	"Breidenbach":                         PLZ{Name: "Breidenbach", Code: []int{35236}},
	"Breitenbach Am Herzberg":             PLZ{Name: "Breitenbach Am Herzberg", Code: []int{36287}},
	"Breitscheid":                         PLZ{Name: "Breitscheid", Code: []int{35767}},
	"Brensbach":                           PLZ{Name: "Brensbach", Code: []int{64395}},
	"Breuberg":                            PLZ{Name: "Breuberg", Code: []int{64747}},
	"Breuna":                              PLZ{Name: "Breuna", Code: []int{34479}},
	"Brombachtal":                         PLZ{Name: "Brombachtal", Code: []int{64753}},
	"Bromskirchen":                        PLZ{Name: "Bromskirchen", Code: []int{59969}},
	"Bruchkobel":                          PLZ{Name: "Bruchkobel", Code: []int{63486}},
	"Budingen":                            PLZ{Name: "Budingen", Code: []int{63654}},
	"Burghaun":                            PLZ{Name: "Burghaun", Code: []int{36151}},
	"Burgwald":                            PLZ{Name: "Burgwald", Code: []int{35099}},
	"Burstadt":                            PLZ{Name: "Burstadt", Code: []int{68642}},
	"Buseck":                              PLZ{Name: "Buseck", Code: []int{35418}},
	"Buttelborn":                          PLZ{Name: "Buttelborn", Code: []int{64572}},
	"Butzbach":                            PLZ{Name: "Butzbach", Code: []int{35510}},
	"Calden":                              PLZ{Name: "Calden", Code: []int{34379}},
	"Colbe":                               PLZ{Name: "Colbe", Code: []int{35091}},
	"Cornberg":                            PLZ{Name: "Cornberg", Code: []int{36219}},
	"Darmstadt":                           PLZ{Name: "Darmstadt", Code: []int{64283, 64285, 64287, 64289, 64291, 64293, 64295, 64297}},
	"Dautphetal":                          PLZ{Name: "Dautphetal", Code: []int{35232}},
	"Dieburg":                             PLZ{Name: "Dieburg", Code: []int{64807}},
	"Diemelsee":                           PLZ{Name: "Diemelsee", Code: []int{34519}},
	"Diemelstadt":                         PLZ{Name: "Diemelstadt", Code: []int{34474}},
	"Dietzenbach":                         PLZ{Name: "Dietzenbach", Code: []int{63128}},
	"Dietzholztal":                        PLZ{Name: "Dietzholztal", Code: []int{35716}},
	"Dillenburg":                          PLZ{Name: "Dillenburg", Code: []int{35683, 35684, 35685, 35686, 35687, 35688, 35689, 35690}},
	"Dipperz":                             PLZ{Name: "Dipperz", Code: []int{36160}},
	"Dornburg":                            PLZ{Name: "Dornburg", Code: []int{65599}},
	"Dreieich":                            PLZ{Name: "Dreieich", Code: []int{63303}},
	"Driedorf":                            PLZ{Name: "Driedorf", Code: []int{35759}},
	"Ebersburg":                           PLZ{Name: "Ebersburg", Code: []int{36157}},
	"Ebsdorfergrund":                      PLZ{Name: "Ebsdorfergrund", Code: []int{35085}},
	"Echzell":                             PLZ{Name: "Echzell", Code: []int{61209}},
	"Edermunde":                           PLZ{Name: "Edermunde", Code: []int{34295}},
	"Edertal":                             PLZ{Name: "Edertal", Code: []int{34549}},
	"Egelsbach":                           PLZ{Name: "Egelsbach", Code: []int{63329}},
	"Ehrenberg":                           PLZ{Name: "Ehrenberg", Code: []int{36115}},
	"Ehringshausen":                       PLZ{Name: "Ehringshausen", Code: []int{35630}},
	"Eichenzell":                          PLZ{Name: "Eichenzell", Code: []int{36124}},
	"Einhausen":                           PLZ{Name: "Einhausen", Code: []int{64683}},
	"Eiterfeld":                           PLZ{Name: "Eiterfeld", Code: []int{36132}},
	"Elbtal":                              PLZ{Name: "Elbtal", Code: []int{65627}},
	"Eltville Am Rhein":                   PLZ{Name: "Eltville Am Rhein", Code: []int{65343, 65344, 65345, 65346, 65347}},
	"Elz":                                 PLZ{Name: "Elz", Code: []int{65604}},
	"Eppertshausen":                       PLZ{Name: "Eppertshausen", Code: []int{64859}},
	"Eppstein":                            PLZ{Name: "Eppstein", Code: []int{65817}},
	"Erbach":                              PLZ{Name: "Erbach", Code: []int{64711}},
	"Erlensee":                            PLZ{Name: "Erlensee", Code: []int{63526}},
	"Erzhausen":                           PLZ{Name: "Erzhausen", Code: []int{64390}},
	"Eschborn":                            PLZ{Name: "Eschborn", Code: []int{65760}},
	"Eschenburg":                          PLZ{Name: "Eschenburg", Code: []int{35713}},
	"Eschwege":                            PLZ{Name: "Eschwege", Code: []int{37269}},
	"Espenau":                             PLZ{Name: "Espenau", Code: []int{34314}},
	"Feldatal":                            PLZ{Name: "Feldatal", Code: []int{36325}},
	"Felsberg":                            PLZ{Name: "Felsberg", Code: []int{34587}},
	"Fernwald":                            PLZ{Name: "Fernwald", Code: []int{35463}},
	"Fischbachtal":                        PLZ{Name: "Fischbachtal", Code: []int{64405}},
	"Flieden":                             PLZ{Name: "Flieden", Code: []int{36103}},
	"Florsbachtal":                        PLZ{Name: "Florsbachtal", Code: []int{63639}},
	"Florsheim":                           PLZ{Name: "Florsheim", Code: []int{65439}},
	"Florstadt":                           PLZ{Name: "Florstadt", Code: []int{61197}},
	"Frankenau":                           PLZ{Name: "Frankenau", Code: []int{35110}},
	"Frankenberg":                         PLZ{Name: "Frankenberg", Code: []int{35066}},
	"Frankfurt Am Main":                   PLZ{Name: "Frankfurt Am Main", Code: []int{60306, 60308, 60310, 60311, 60313, 60314, 60316, 60318, 60320, 60322, 60323, 60325, 60326, 60327, 60329, 60385, 60386, 60388, 60389, 60431, 60433, 60435, 60437, 60438, 60439, 60486, 60487, 60488, 60489, 60528, 60529, 60549, 60594, 60596, 60598, 60599, 65929, 65931, 65933, 65934, 65936}},
	"Frankisch-Crumbach":                  PLZ{Name: "Frankisch-Crumbach", Code: []int{64407}},
	"Freiensteinau":                       PLZ{Name: "Freiensteinau", Code: []int{36399}},
	"Freigericht":                         PLZ{Name: "Freigericht", Code: []int{63579}},
	"Friedberg":                           PLZ{Name: "Friedberg", Code: []int{61169}},
	"Friedewald":                          PLZ{Name: "Friedewald", Code: []int{36289}},
	"Friedrichsdorf":                      PLZ{Name: "Friedrichsdorf", Code: []int{61381}},
	"Frielendorf":                         PLZ{Name: "Frielendorf", Code: []int{34621}},
	"Fritzlar":                            PLZ{Name: "Fritzlar", Code: []int{34560}},
	"Fronhausen":                          PLZ{Name: "Fronhausen", Code: []int{35112}},
	"Fulda":                               PLZ{Name: "Fulda", Code: []int{36037, 36039, 36041, 36043}},
	"Fuldabruck":                          PLZ{Name: "Fuldabruck", Code: []int{34277}},
	"Fuldatal":                            PLZ{Name: "Fuldatal", Code: []int{34233}},
	"Furth":                               PLZ{Name: "Furth", Code: []int{64658}},
	"Gedern":                              PLZ{Name: "Gedern", Code: []int{63688}},
	"Geisenheim":                          PLZ{Name: "Geisenheim", Code: []int{65366}},
	"Gelnhausen":                          PLZ{Name: "Gelnhausen", Code: []int{63571}},
	"Gemunden":                            PLZ{Name: "Gemunden", Code: []int{35285, 35329}},
	"Gernsheim":                           PLZ{Name: "Gernsheim", Code: []int{64579}},
	"Gersfeld":                            PLZ{Name: "Gersfeld", Code: []int{36129}},
	"Giesen":                              PLZ{Name: "Giesen", Code: []int{35390, 35392, 35394, 35396, 35398}},
	"Gilserberg":                          PLZ{Name: "Gilserberg", Code: []int{34630}},
	"Ginsheim-Gustavsburg":                PLZ{Name: "Ginsheim-Gustavsburg", Code: []int{65462}},
	"Gladenbach":                          PLZ{Name: "Gladenbach", Code: []int{35075}},
	"Glashutten":                          PLZ{Name: "Glashutten", Code: []int{61479}},
	"Glauburg":                            PLZ{Name: "Glauburg", Code: []int{63695}},
	"Gorxheimertal":                       PLZ{Name: "Gorxheimertal", Code: []int{69517}},
	"Grasellenbach":                       PLZ{Name: "Grasellenbach", Code: []int{64689}},
	"Gravenwiesbach":                      PLZ{Name: "Gravenwiesbach", Code: []int{61279}},
	"Grebenau":                            PLZ{Name: "Grebenau", Code: []int{36323}},
	"Grebenhain":                          PLZ{Name: "Grebenhain", Code: []int{36355}},
	"Grebenstein":                         PLZ{Name: "Grebenstein", Code: []int{34393}},
	"Greifenstein":                        PLZ{Name: "Greifenstein", Code: []int{35753}},
	"Griesheim":                           PLZ{Name: "Griesheim", Code: []int{64347}},
	"Gros-Bieberau":                       PLZ{Name: "Gros-Bieberau", Code: []int{64401}},
	"Gros-Gerau":                          PLZ{Name: "Gros-Gerau", Code: []int{64521}},
	"Gros-Rohrheim":                       PLZ{Name: "Gros-Rohrheim", Code: []int{68649}},
	"Gros-Umstadt":                        PLZ{Name: "Gros-Umstadt", Code: []int{64823}},
	"Gros-Zimmern":                        PLZ{Name: "Gros-Zimmern", Code: []int{64846}},
	"Grosalmerode":                        PLZ{Name: "Grosalmerode", Code: []int{37247}},
	"Grosenluder":                         PLZ{Name: "Grosenluder", Code: []int{36137}},
	"Groskrotzenburg":                     PLZ{Name: "Groskrotzenburg", Code: []int{63538}},
	"Grunberg":                            PLZ{Name: "Grunberg", Code: []int{35305}},
	"Grundau":                             PLZ{Name: "Grundau", Code: []int{63584}},
	"Gudensberg":                          PLZ{Name: "Gudensberg", Code: []int{34281}},
	"Guxhagen":                            PLZ{Name: "Guxhagen", Code: []int{34302}},
	"Habichtswald":                        PLZ{Name: "Habichtswald", Code: []int{34317}},
	"Hadamar":                             PLZ{Name: "Hadamar", Code: []int{65589}},
	"Haiger":                              PLZ{Name: "Haiger", Code: []int{35708}},
	"Haina":                               PLZ{Name: "Haina", Code: []int{35114}},
	"Hainburg":                            PLZ{Name: "Hainburg", Code: []int{63512}},
	"Hammersbach":                         PLZ{Name: "Hammersbach", Code: []int{63546}},
	"Hanau":                               PLZ{Name: "Hanau", Code: []int{63405, 63450, 63452, 63454, 63456, 63457}},
	"Hasselroth":                          PLZ{Name: "Hasselroth", Code: []int{63594}},
	"Hattersheim":                         PLZ{Name: "Hattersheim", Code: []int{65795}},
	"Hatzfeld":                            PLZ{Name: "Hatzfeld", Code: []int{35116}},
	"Hauneck":                             PLZ{Name: "Hauneck", Code: []int{36282}},
	"Haunetal":                            PLZ{Name: "Haunetal", Code: []int{36166}},
	"Heidenrod":                           PLZ{Name: "Heidenrod", Code: []int{65321}},
	"Helsa":                               PLZ{Name: "Helsa", Code: []int{34298}},
	"Heppenheim":                          PLZ{Name: "Heppenheim", Code: []int{64646}},
	"Herborn":                             PLZ{Name: "Herborn", Code: []int{35745}},
	"Herbstein":                           PLZ{Name: "Herbstein", Code: []int{36358}},
	"Heringen":                            PLZ{Name: "Heringen", Code: []int{36266}},
	"Herleshausen":                        PLZ{Name: "Herleshausen", Code: []int{37293}},
	"Hesseneck":                           PLZ{Name: "Hesseneck", Code: []int{64754}},
	"Hessisch Lichtenau":                  PLZ{Name: "Hessisch Lichtenau", Code: []int{37235}},
	"Heuchelheim":                         PLZ{Name: "Heuchelheim", Code: []int{35452}},
	"Heusenstamm":                         PLZ{Name: "Heusenstamm", Code: []int{63150}},
	"Hilders":                             PLZ{Name: "Hilders", Code: []int{36115}},
	"Hirschhorn":                          PLZ{Name: "Hirschhorn", Code: []int{69434}},
	"Hirzenhain":                          PLZ{Name: "Hirzenhain", Code: []int{63697}},
	"Hochheim Am Main":                    PLZ{Name: "Hochheim Am Main", Code: []int{65239}},
	"Hochst Im Odenwald":                  PLZ{Name: "Hochst Im Odenwald", Code: []int{64739}},
	"Hofbieber":                           PLZ{Name: "Hofbieber", Code: []int{36145}},
	"Hofgeismar":                          PLZ{Name: "Hofgeismar", Code: []int{34369}},
	"Hofheim Am Taunus":                   PLZ{Name: "Hofheim Am Taunus", Code: []int{65719}},
	"Hohenahr":                            PLZ{Name: "Hohenahr", Code: []int{35644}},
	"Hohenroda":                           PLZ{Name: "Hohenroda", Code: []int{36284}},
	"Hohenstein":                          PLZ{Name: "Hohenstein", Code: []int{65329}},
	"Homberg":                             PLZ{Name: "Homberg", Code: []int{34576, 35315}},
	"Hosenfeld":                           PLZ{Name: "Hosenfeld", Code: []int{36154}},
	"Hunfeld":                             PLZ{Name: "Hunfeld", Code: []int{36088}},
	"Hunfelden":                           PLZ{Name: "Hunfelden", Code: []int{65597}},
	"Hungen":                              PLZ{Name: "Hungen", Code: []int{35410}},
	"Hunstetten":                          PLZ{Name: "Hunstetten", Code: []int{65510}},
	"Huttenberg":                          PLZ{Name: "Huttenberg", Code: []int{35625}},
	"Idstein":                             PLZ{Name: "Idstein", Code: []int{65510}},
	"Immenhausen":                         PLZ{Name: "Immenhausen", Code: []int{34376}},
	"Jesberg":                             PLZ{Name: "Jesberg", Code: []int{34632}},
	"Jossgrund":                           PLZ{Name: "Jossgrund", Code: []int{63637}},
	"Kalbach":                             PLZ{Name: "Kalbach", Code: []int{36148}},
	"Karben":                              PLZ{Name: "Karben", Code: []int{61184}},
	"Kassel":                              PLZ{Name: "Kassel", Code: []int{34117, 34119, 34121, 34123, 34125, 34127, 34128, 34130, 34131, 34132, 34134}},
	"Kaufungen":                           PLZ{Name: "Kaufungen", Code: []int{34260}},
	"Kefenrod":                            PLZ{Name: "Kefenrod", Code: []int{63699}},
	"Kelkheim":                            PLZ{Name: "Kelkheim", Code: []int{65779}},
	"Kelsterbach":                         PLZ{Name: "Kelsterbach", Code: []int{65451}},
	"Kiedrich":                            PLZ{Name: "Kiedrich", Code: []int{65399}},
	"Kirchhain":                           PLZ{Name: "Kirchhain", Code: []int{35274}},
	"Kirchheim":                           PLZ{Name: "Kirchheim", Code: []int{36275}},
	"Kirtorf":                             PLZ{Name: "Kirtorf", Code: []int{36320}},
	"Knullwald":                           PLZ{Name: "Knullwald", Code: []int{34593}},
	"Konigstein Im Taunus":                PLZ{Name: "Konigstein Im Taunus", Code: []int{61462}},
	"Konigstein Im Taunus Falkenstein":    PLZ{Name: "Konigstein Im Taunus Falkenstein", Code: []int{61462}},
	"Konigstein Im Taunus Mammolshain":    PLZ{Name: "Konigstein Im Taunus Mammolshain", Code: []int{61462}},
	"Konigstein Im Taunus Schneidhain":    PLZ{Name: "Konigstein Im Taunus Schneidhain", Code: []int{61462}},
	"Korbach":                             PLZ{Name: "Korbach", Code: []int{34497}},
	"Korle":                               PLZ{Name: "Korle", Code: []int{34327}},
	"Kriftel":                             PLZ{Name: "Kriftel", Code: []int{65830}},
	"Kronberg Im Taunus":                  PLZ{Name: "Kronberg Im Taunus", Code: []int{61476}},
	"Kunzell":                             PLZ{Name: "Kunzell", Code: []int{36093}},
	"Lahnau":                              PLZ{Name: "Lahnau", Code: []int{35633}},
	"Lahntal":                             PLZ{Name: "Lahntal", Code: []int{35094}},
	"Lampertheim":                         PLZ{Name: "Lampertheim", Code: []int{68623}},
	"Langen":                              PLZ{Name: "Langen", Code: []int{63225}},
	"Langenselbold":                       PLZ{Name: "Langenselbold", Code: []int{63505}},
	"Langgons":                            PLZ{Name: "Langgons", Code: []int{35428}},
	"Laubach":                             PLZ{Name: "Laubach", Code: []int{35321}},
	"Lauterbach":                          PLZ{Name: "Lauterbach", Code: []int{36341}},
	"Lautertal":                           PLZ{Name: "Lautertal", Code: []int{36369, 64686}},
	"Leun":                                PLZ{Name: "Leun", Code: []int{35638}},
	"Lich":                                PLZ{Name: "Lich", Code: []int{35423}},
	"Lichtenfels":                         PLZ{Name: "Lichtenfels", Code: []int{35104}},
	"Liebenau":                            PLZ{Name: "Liebenau", Code: []int{34396}},
	"Liederbach Am Taunus":                PLZ{Name: "Liederbach Am Taunus", Code: []int{65835}},
	"Limburg An Der Lahn":                 PLZ{Name: "Limburg An Der Lahn", Code: []int{65549, 65550, 65551, 65552, 65553, 65554, 65555, 65556}},
	"Limeshain":                           PLZ{Name: "Limeshain", Code: []int{63694}},
	"Linden":                              PLZ{Name: "Linden", Code: []int{35440}},
	"Lindenfels":                          PLZ{Name: "Lindenfels", Code: []int{64678}},
	"Linsengericht":                       PLZ{Name: "Linsengericht", Code: []int{63589}},
	"Lohfelden":                           PLZ{Name: "Lohfelden", Code: []int{34253}},
	"Lohnberg":                            PLZ{Name: "Lohnberg", Code: []int{35792}},
	"Lohra":                               PLZ{Name: "Lohra", Code: []int{35102}},
	"Lollar":                              PLZ{Name: "Lollar", Code: []int{35457}},
	"Lorch":                               PLZ{Name: "Lorch", Code: []int{65391}},
	"Lorsch":                              PLZ{Name: "Lorsch", Code: []int{64653}},
	"Ludwigsau":                           PLZ{Name: "Ludwigsau", Code: []int{36251}},
	"Lutzelbach":                          PLZ{Name: "Lutzelbach", Code: []int{64750}},
	"Mainhausen":                          PLZ{Name: "Mainhausen", Code: []int{63533}},
	"Maintal":                             PLZ{Name: "Maintal", Code: []int{63477}},
	"Mainz-Kastel":                        PLZ{Name: "Mainz-Kastel", Code: []int{55252}},
	"Mainz-Kostheim":                      PLZ{Name: "Mainz-Kostheim", Code: []int{55246}},
	"Malsfeld":                            PLZ{Name: "Malsfeld", Code: []int{34323}},
	"Marburg":                             PLZ{Name: "Marburg", Code: []int{35037, 35039, 35041, 35043}},
	"Meinhard":                            PLZ{Name: "Meinhard", Code: []int{37276}},
	"Meisner":                             PLZ{Name: "Meisner", Code: []int{37290}},
	"Melsungen":                           PLZ{Name: "Melsungen", Code: []int{34212}},
	"Mengerskirchen":                      PLZ{Name: "Mengerskirchen", Code: []int{35794}},
	"Merenberg":                           PLZ{Name: "Merenberg", Code: []int{35799}},
	"Messel":                              PLZ{Name: "Messel", Code: []int{64409}},
	"Michelstadt":                         PLZ{Name: "Michelstadt", Code: []int{64720}},
	"Mittenaar":                           PLZ{Name: "Mittenaar", Code: []int{35756}},
	"Modautal":                            PLZ{Name: "Modautal", Code: []int{64397}},
	"Morfelden-Walldorf":                  PLZ{Name: "Morfelden-Walldorf", Code: []int{64546}},
	"Morlenbach":                          PLZ{Name: "Morlenbach", Code: []int{69509}},
	"Morschen":                            PLZ{Name: "Morschen", Code: []int{34326}},
	"Mossautal":                           PLZ{Name: "Mossautal", Code: []int{64756}},
	"Mucke":                               PLZ{Name: "Mucke", Code: []int{35325}},
	"Muhlheim":                            PLZ{Name: "Muhlheim", Code: []int{63165}},
	"Muhltal":                             PLZ{Name: "Muhltal", Code: []int{64367}},
	"Munchhausen":                         PLZ{Name: "Munchhausen", Code: []int{35117}},
	"Munster":                             PLZ{Name: "Munster", Code: []int{64839}},
	"Munzenberg":                          PLZ{Name: "Munzenberg", Code: []int{35516}},
	"Nauheim":                             PLZ{Name: "Nauheim", Code: []int{64569}},
	"Naumburg":                            PLZ{Name: "Naumburg", Code: []int{34311}},
	"Neckarsteinach":                      PLZ{Name: "Neckarsteinach", Code: []int{69239}},
	"Nentershausen":                       PLZ{Name: "Nentershausen", Code: []int{36214}},
	"Neu-Anspach":                         PLZ{Name: "Neu-Anspach", Code: []int{61267}},
	"Neu-Eichenberg":                      PLZ{Name: "Neu-Eichenberg", Code: []int{37249}},
	"Neu-Isenburg":                        PLZ{Name: "Neu-Isenburg", Code: []int{63263}},
	"Neuberg":                             PLZ{Name: "Neuberg", Code: []int{63543}},
	"Neuenstein":                          PLZ{Name: "Neuenstein", Code: []int{36286}},
	"Neuental":                            PLZ{Name: "Neuental", Code: []int{34599}},
	"Neuhof":                              PLZ{Name: "Neuhof", Code: []int{36119}},
	"Neukirchen":                          PLZ{Name: "Neukirchen", Code: []int{34626}},
	"Neustadt":                            PLZ{Name: "Neustadt", Code: []int{35279}},
	"Nidda":                               PLZ{Name: "Nidda", Code: []int{63667}},
	"Niddatal":                            PLZ{Name: "Niddatal", Code: []int{61194}},
	"Nidderau":                            PLZ{Name: "Nidderau", Code: []int{61130}},
	"Niedenstein":                         PLZ{Name: "Niedenstein", Code: []int{34305}},
	"Niederaula":                          PLZ{Name: "Niederaula", Code: []int{36272}},
	"Niederdorfelden":                     PLZ{Name: "Niederdorfelden", Code: []int{61138}},
	"Niedernhausen":                       PLZ{Name: "Niedernhausen", Code: []int{65527}},
	"Nieste":                              PLZ{Name: "Nieste", Code: []int{34329}},
	"Niestetal":                           PLZ{Name: "Niestetal", Code: []int{34266}},
	"Nusttal":                             PLZ{Name: "Nusttal", Code: []int{36167}},
	"Ober-Morlen":                         PLZ{Name: "Ober-Morlen", Code: []int{61239}},
	"Ober-Ramstadt":                       PLZ{Name: "Ober-Ramstadt", Code: []int{64372}},
	"Oberaula":                            PLZ{Name: "Oberaula", Code: []int{36280}},
	"Obertshausen":                        PLZ{Name: "Obertshausen", Code: []int{63179}},
	"Oberursel":                           PLZ{Name: "Oberursel", Code: []int{61440}},
	"Oberweser":                           PLZ{Name: "Oberweser", Code: []int{34399}},
	"Oestrich-Winkel":                     PLZ{Name: "Oestrich-Winkel", Code: []int{65375}},
	"Offenbach":                           PLZ{Name: "Offenbach", Code: []int{63065, 63067, 63069, 63071, 63073, 63075}},
	"Ortenberg":                           PLZ{Name: "Ortenberg", Code: []int{63683}},
	"Ottrau":                              PLZ{Name: "Ottrau", Code: []int{34633}},
	"Otzberg":                             PLZ{Name: "Otzberg", Code: []int{64853}},
	"Petersberg":                          PLZ{Name: "Petersberg", Code: []int{36100}},
	"Pfungstadt":                          PLZ{Name: "Pfungstadt", Code: []int{64319}},
	"Philippsthal":                        PLZ{Name: "Philippsthal", Code: []int{36269}},
	"Pohlheim":                            PLZ{Name: "Pohlheim", Code: []int{35415}},
	"Poppenhausen":                        PLZ{Name: "Poppenhausen", Code: []int{36163}},
	"Rabenau":                             PLZ{Name: "Rabenau", Code: []int{35466}},
	"Ranstadt":                            PLZ{Name: "Ranstadt", Code: []int{63691}},
	"Rasdorf":                             PLZ{Name: "Rasdorf", Code: []int{36169}},
	"Raunheim":                            PLZ{Name: "Raunheim", Code: []int{65479}},
	"Rauschenberg":                        PLZ{Name: "Rauschenberg", Code: []int{35282}},
	"Reichelsheim":                        PLZ{Name: "Reichelsheim", Code: []int{61203, 64385}},
	"Reinhardshagen":                      PLZ{Name: "Reinhardshagen", Code: []int{34359}},
	"Reinheim":                            PLZ{Name: "Reinheim", Code: []int{64354}},
	"Reiskirchen":                         PLZ{Name: "Reiskirchen", Code: []int{35447}},
	"Riedstadt":                           PLZ{Name: "Riedstadt", Code: []int{64560}},
	"Rimbach":                             PLZ{Name: "Rimbach", Code: []int{64668}},
	"Ringgau":                             PLZ{Name: "Ringgau", Code: []int{37296}},
	"Rockenberg":                          PLZ{Name: "Rockenberg", Code: []int{35519}},
	"Rodenbach":                           PLZ{Name: "Rodenbach", Code: []int{63517}},
	"Rodermark":                           PLZ{Name: "Rodermark", Code: []int{63322}},
	"Rodgau":                              PLZ{Name: "Rodgau", Code: []int{63110}},
	"Romrod":                              PLZ{Name: "Romrod", Code: []int{36329}},
	"Ronneburg":                           PLZ{Name: "Ronneburg", Code: []int{63549}},
	"Ronshausen":                          PLZ{Name: "Ronshausen", Code: []int{36217}},
	"Rosbach Vor Der Hohe":                PLZ{Name: "Rosbach Vor Der Hohe", Code: []int{61191}},
	"Rosbach Vor Der Hohe Nieder-Rosbach": PLZ{Name: "Rosbach Vor Der Hohe Nieder-Rosbach", Code: []int{61191}},
	"Rosbach Vor Der Hohe Ober-Rosbach":   PLZ{Name: "Rosbach Vor Der Hohe Ober-Rosbach", Code: []int{61191}},
	"Rosbach Vor Der Hohe Rodheim Vor Der Hohe": PLZ{Name: "Rosbach Vor Der Hohe Rodheim Vor Der Hohe", Code: []int{61191}},
	"Rosdorf":                PLZ{Name: "Rosdorf", Code: []int{64380}},
	"Rosenthal":              PLZ{Name: "Rosenthal", Code: []int{35119}},
	"Rotenburg An Der Fulda": PLZ{Name: "Rotenburg An Der Fulda", Code: []int{36199}},
	"Rothenberg":             PLZ{Name: "Rothenberg", Code: []int{64757}},
	"Rudesheim Am Rhein":     PLZ{Name: "Rudesheim Am Rhein", Code: []int{65385}},
	"Runkel":                 PLZ{Name: "Runkel", Code: []int{65594}},
	"Russelsheim":            PLZ{Name: "Russelsheim", Code: []int{65428}},
	"Schaafheim":             PLZ{Name: "Schaafheim", Code: []int{64850}},
	"Schauenburg":            PLZ{Name: "Schauenburg", Code: []int{34270}},
	"Schenklengsfeld":        PLZ{Name: "Schenklengsfeld", Code: []int{36277}},
	"Schlangenbad":           PLZ{Name: "Schlangenbad", Code: []int{65388}},
	"Schlitz":                PLZ{Name: "Schlitz", Code: []int{36110}},
	"Schluchtern":            PLZ{Name: "Schluchtern", Code: []int{36381}},
	"Schmitten":              PLZ{Name: "Schmitten", Code: []int{61389}},
	"Schoffengrund":          PLZ{Name: "Schoffengrund", Code: []int{35641}},
	"Schoneck":               PLZ{Name: "Schoneck", Code: []int{61137}},
	"Schotten":               PLZ{Name: "Schotten", Code: []int{63679}},
	"Schrecksbach":           PLZ{Name: "Schrecksbach", Code: []int{34637}},
	"Schwalbach Am Taunus":   PLZ{Name: "Schwalbach Am Taunus", Code: []int{65824}},
	"Schwalmstadt":           PLZ{Name: "Schwalmstadt", Code: []int{34613}},
	"Schwalmtal":             PLZ{Name: "Schwalmtal", Code: []int{36318}},
	"Schwarzenborn":          PLZ{Name: "Schwarzenborn", Code: []int{34639}},
	"Seeheim-Jugenheim":      PLZ{Name: "Seeheim-Jugenheim", Code: []int{64342}},
	"Seligenstadt":           PLZ{Name: "Seligenstadt", Code: []int{63500}},
	"Selters":                PLZ{Name: "Selters", Code: []int{65618}},
	"Siegbach":               PLZ{Name: "Siegbach", Code: []int{35768}},
	"Sinn":                   PLZ{Name: "Sinn", Code: []int{35764}},
	"Sinntal":                PLZ{Name: "Sinntal", Code: []int{36391}},
	"Sohrewald":              PLZ{Name: "Sohrewald", Code: []int{34320}},
	"Solms":                  PLZ{Name: "Solms", Code: []int{35606}},
	"Sontra":                 PLZ{Name: "Sontra", Code: []int{36205}},
	"Spangenberg":            PLZ{Name: "Spangenberg", Code: []int{34286}},
	"Stadtallendorf":         PLZ{Name: "Stadtallendorf", Code: []int{35260}},
	"Staufenberg":            PLZ{Name: "Staufenberg", Code: []int{35460}},
	"Steffenberg":            PLZ{Name: "Steffenberg", Code: []int{35239}},
	"Steinau An Der Strase":  PLZ{Name: "Steinau An Der Strase", Code: []int{36396}},
	"Steinbach":              PLZ{Name: "Steinbach", Code: []int{61449}},
	"Stockstadt Am Rhein":    PLZ{Name: "Stockstadt Am Rhein", Code: []int{64589}},
	"Sulzbach":               PLZ{Name: "Sulzbach", Code: []int{65843}},
	"Tann":                   PLZ{Name: "Tann", Code: []int{36142}},
	"Taunusstein":            PLZ{Name: "Taunusstein", Code: []int{65219, 65220, 65221, 65222, 65223, 65224, 65232}},
	"Trebur":                 PLZ{Name: "Trebur", Code: []int{65468}},
	"Trendelburg":            PLZ{Name: "Trendelburg", Code: []int{34388}},
	"Twistetal":              PLZ{Name: "Twistetal", Code: []int{34477}},
	"Ulrichstein":            PLZ{Name: "Ulrichstein", Code: []int{35327}},
	"Usingen":                PLZ{Name: "Usingen", Code: []int{61250}},
	"Vellmar":                PLZ{Name: "Vellmar", Code: []int{34246}},
	"Viernheim":              PLZ{Name: "Viernheim", Code: []int{68519}},
	"Villmar":                PLZ{Name: "Villmar", Code: []int{65606}},
	"Vohl":                   PLZ{Name: "Vohl", Code: []int{34516}},
	"Volkmarsen":             PLZ{Name: "Volkmarsen", Code: []int{34471}},
	"Wabern":                 PLZ{Name: "Wabern", Code: []int{34590}},
	"Wachtersbach":           PLZ{Name: "Wachtersbach", Code: []int{63607}},
	"Wald-Michelbach":        PLZ{Name: "Wald-Michelbach", Code: []int{69483}},
	"Waldbrunn":              PLZ{Name: "Waldbrunn", Code: []int{65620}},
	"Waldeck":                PLZ{Name: "Waldeck", Code: []int{34513}},
	"Waldems":                PLZ{Name: "Waldems", Code: []int{65529}},
	"Waldkappel":             PLZ{Name: "Waldkappel", Code: []int{37284}},
	"Waldsolms":              PLZ{Name: "Waldsolms", Code: []int{35647}},
	"Walluf":                 PLZ{Name: "Walluf", Code: []int{65396}},
	"Wanfried":               PLZ{Name: "Wanfried", Code: []int{37281}},
	"Wartenberg":             PLZ{Name: "Wartenberg", Code: []int{36367}},
	"Wehretal":               PLZ{Name: "Wehretal", Code: []int{37287}},
	"Wehrheim":               PLZ{Name: "Wehrheim", Code: []int{61273}},
	"Weilburg":               PLZ{Name: "Weilburg", Code: []int{35781}},
	"Weilmunster":            PLZ{Name: "Weilmunster", Code: []int{35789}},
	"Weilrod":                PLZ{Name: "Weilrod", Code: []int{61276}},
	"Weimar":                 PLZ{Name: "Weimar", Code: []int{35096}},
	"Weinbach":               PLZ{Name: "Weinbach", Code: []int{35796}},
	"Weisenborn":             PLZ{Name: "Weisenborn", Code: []int{37299}},
	"Weiterstadt":            PLZ{Name: "Weiterstadt", Code: []int{64331}},
	"Wettenberg":             PLZ{Name: "Wettenberg", Code: []int{35435}},
	"Wetter":                 PLZ{Name: "Wetter", Code: []int{35083}},
	"Wetzlar":                PLZ{Name: "Wetzlar", Code: []int{35576, 35578, 35579, 35580, 35581, 35582, 35583, 35584, 35585, 35586}},
	"Wiesbaden":              PLZ{Name: "Wiesbaden", Code: []int{65183, 65185, 65187, 65189, 65191, 65193, 65195, 65197, 65199, 65201, 65203, 65205, 65207}},
	"Wildeck":                PLZ{Name: "Wildeck", Code: []int{36208}},
	"Willingen":              PLZ{Name: "Willingen", Code: []int{34508}},
	"Willingshausen":         PLZ{Name: "Willingshausen", Code: []int{34628}},
	"Witzenhausen":           PLZ{Name: "Witzenhausen", Code: []int{37213, 37214, 37215, 37216, 37217, 37218}},
	"Wohratal":               PLZ{Name: "Wohratal", Code: []int{35288}},
	"Wolfersheim":            PLZ{Name: "Wolfersheim", Code: []int{61200}},
	"Wolfhagen":              PLZ{Name: "Wolfhagen", Code: []int{34466}},
	"Wollstadt":              PLZ{Name: "Wollstadt", Code: []int{61206}},
	"Zierenberg":             PLZ{Name: "Zierenberg", Code: []int{34289}},
	"Zwingenberg":            PLZ{Name: "Zwingenberg", Code: []int{64673}},
}
var hessen_slice = []PLZ{
	PLZ{Name: "Aarbergen", Code: []int{65326}},
	PLZ{Name: "Abtsteinach", Code: []int{69518}},
	PLZ{Name: "Ahnatal", Code: []int{34292}},
	PLZ{Name: "Alheim", Code: []int{36211}},
	PLZ{Name: "Allendorf", Code: []int{35108, 35469}},
	PLZ{Name: "Allendorf Battenfeld", Code: []int{35108}},
	PLZ{Name: "Allendorf Haine", Code: []int{35108}},
	PLZ{Name: "Allendorf Osterfeld", Code: []int{35108}},
	PLZ{Name: "Allendorf Rennertehausen", Code: []int{35108}},
	PLZ{Name: "Alsbach-Hahnlein", Code: []int{64665}},
	PLZ{Name: "Alsfeld", Code: []int{36304}},
	PLZ{Name: "Altenstadt", Code: []int{63674}},
	PLZ{Name: "Amoneburg", Code: []int{35287}},
	PLZ{Name: "Angelburg", Code: []int{35719}},
	PLZ{Name: "Antrifttal", Code: []int{36326}},
	PLZ{Name: "Aslar", Code: []int{35614}},
	PLZ{Name: "Babenhausen", Code: []int{64832}},
	PLZ{Name: "Bad Arolsen", Code: []int{34454}},
	PLZ{Name: "Bad Camberg", Code: []int{65520}},
	PLZ{Name: "Bad Emstal", Code: []int{34308}},
	PLZ{Name: "Bad Endbach", Code: []int{35080}},
	PLZ{Name: "Bad Hersfeld", Code: []int{36251}},
	PLZ{Name: "Bad Homburg Vor Der Hohe", Code: []int{61348, 61350, 61352}},
	PLZ{Name: "Bad Karlshafen", Code: []int{34385}},
	PLZ{Name: "Bad Konig", Code: []int{64732}},
	PLZ{Name: "Bad Nauheim", Code: []int{61231}},
	PLZ{Name: "Bad Orb", Code: []int{63619}},
	PLZ{Name: "Bad Salzschlirf", Code: []int{36364}},
	PLZ{Name: "Bad Schwalbach", Code: []int{65307}},
	PLZ{Name: "Bad Soden Am Taunus", Code: []int{65812}},
	PLZ{Name: "Bad Soden-Salmunster", Code: []int{63628}},
	PLZ{Name: "Bad Sooden-Allendorf", Code: []int{37242}},
	PLZ{Name: "Bad Vilbel", Code: []int{61118}},
	PLZ{Name: "Bad Wildungen", Code: []int{34537}},
	PLZ{Name: "Bad Zwesten", Code: []int{34596}},
	PLZ{Name: "Battenberg", Code: []int{35088}},
	PLZ{Name: "Baunatal", Code: []int{34225}},
	PLZ{Name: "Bebra", Code: []int{36179}},
	PLZ{Name: "Beerfelden", Code: []int{64743}},
	PLZ{Name: "Bensheim", Code: []int{64625}},
	PLZ{Name: "Berkatal", Code: []int{37297}},
	PLZ{Name: "Beselich", Code: []int{65614}},
	PLZ{Name: "Biblis", Code: []int{68647}},
	PLZ{Name: "Bickenbach", Code: []int{64404}},
	PLZ{Name: "Biebergemund", Code: []int{63599}},
	PLZ{Name: "Biebertal", Code: []int{35444}},
	PLZ{Name: "Biebesheim Am Rhein", Code: []int{64584}},
	PLZ{Name: "Biedenkopf", Code: []int{35216}},
	PLZ{Name: "Birkenau", Code: []int{69488}},
	PLZ{Name: "Birstein", Code: []int{63633}},
	PLZ{Name: "Bischoffen", Code: []int{35649}},
	PLZ{Name: "Bischofsheim", Code: []int{65474}},
	PLZ{Name: "Borken", Code: []int{34582}},
	PLZ{Name: "Brachttal", Code: []int{63636}},
	PLZ{Name: "Braunfels", Code: []int{35619}},
	PLZ{Name: "Braunfels Altenkirchen", Code: []int{35619}},
	PLZ{Name: "Braunfels Bonbaden", Code: []int{35619}},
	PLZ{Name: "Braunfels Braunfels", Code: []int{35619}},
	PLZ{Name: "Braunfels Neukirchen", Code: []int{35619}},
	PLZ{Name: "Braunfels Philippstein", Code: []int{35619}},
	PLZ{Name: "Braunfels Tiefenbach", Code: []int{35619}},
	PLZ{Name: "Brechen", Code: []int{65611}},
	PLZ{Name: "Breidenbach", Code: []int{35236}},
	PLZ{Name: "Breitenbach Am Herzberg", Code: []int{36287}},
	PLZ{Name: "Breitscheid", Code: []int{35767}},
	PLZ{Name: "Brensbach", Code: []int{64395}},
	PLZ{Name: "Breuberg", Code: []int{64747}},
	PLZ{Name: "Breuna", Code: []int{34479}},
	PLZ{Name: "Brombachtal", Code: []int{64753}},
	PLZ{Name: "Bromskirchen", Code: []int{59969}},
	PLZ{Name: "Bruchkobel", Code: []int{63486}},
	PLZ{Name: "Budingen", Code: []int{63654}},
	PLZ{Name: "Burghaun", Code: []int{36151}},
	PLZ{Name: "Burgwald", Code: []int{35099}},
	PLZ{Name: "Burstadt", Code: []int{68642}},
	PLZ{Name: "Buseck", Code: []int{35418}},
	PLZ{Name: "Buttelborn", Code: []int{64572}},
	PLZ{Name: "Butzbach", Code: []int{35510}},
	PLZ{Name: "Calden", Code: []int{34379}},
	PLZ{Name: "Colbe", Code: []int{35091}},
	PLZ{Name: "Cornberg", Code: []int{36219}},
	PLZ{Name: "Darmstadt", Code: []int{64283, 64285, 64287, 64289, 64291, 64293, 64295, 64297}},
	PLZ{Name: "Dautphetal", Code: []int{35232}},
	PLZ{Name: "Dieburg", Code: []int{64807}},
	PLZ{Name: "Diemelsee", Code: []int{34519}},
	PLZ{Name: "Diemelstadt", Code: []int{34474}},
	PLZ{Name: "Dietzenbach", Code: []int{63128}},
	PLZ{Name: "Dietzholztal", Code: []int{35716}},
	PLZ{Name: "Dillenburg", Code: []int{35683, 35684, 35685, 35686, 35687, 35688, 35689, 35690}},
	PLZ{Name: "Dipperz", Code: []int{36160}},
	PLZ{Name: "Dornburg", Code: []int{65599}},
	PLZ{Name: "Dreieich", Code: []int{63303}},
	PLZ{Name: "Driedorf", Code: []int{35759}},
	PLZ{Name: "Ebersburg", Code: []int{36157}},
	PLZ{Name: "Ebsdorfergrund", Code: []int{35085}},
	PLZ{Name: "Echzell", Code: []int{61209}},
	PLZ{Name: "Edermunde", Code: []int{34295}},
	PLZ{Name: "Edertal", Code: []int{34549}},
	PLZ{Name: "Egelsbach", Code: []int{63329}},
	PLZ{Name: "Ehrenberg", Code: []int{36115}},
	PLZ{Name: "Ehringshausen", Code: []int{35630}},
	PLZ{Name: "Eichenzell", Code: []int{36124}},
	PLZ{Name: "Einhausen", Code: []int{64683}},
	PLZ{Name: "Eiterfeld", Code: []int{36132}},
	PLZ{Name: "Elbtal", Code: []int{65627}},
	PLZ{Name: "Eltville Am Rhein", Code: []int{65343, 65344, 65345, 65346, 65347}},
	PLZ{Name: "Elz", Code: []int{65604}},
	PLZ{Name: "Eppertshausen", Code: []int{64859}},
	PLZ{Name: "Eppstein", Code: []int{65817}},
	PLZ{Name: "Erbach", Code: []int{64711}},
	PLZ{Name: "Erlensee", Code: []int{63526}},
	PLZ{Name: "Erzhausen", Code: []int{64390}},
	PLZ{Name: "Eschborn", Code: []int{65760}},
	PLZ{Name: "Eschenburg", Code: []int{35713}},
	PLZ{Name: "Eschwege", Code: []int{37269}},
	PLZ{Name: "Espenau", Code: []int{34314}},
	PLZ{Name: "Feldatal", Code: []int{36325}},
	PLZ{Name: "Felsberg", Code: []int{34587}},
	PLZ{Name: "Fernwald", Code: []int{35463}},
	PLZ{Name: "Fischbachtal", Code: []int{64405}},
	PLZ{Name: "Flieden", Code: []int{36103}},
	PLZ{Name: "Florsbachtal", Code: []int{63639}},
	PLZ{Name: "Florsheim", Code: []int{65439}},
	PLZ{Name: "Florstadt", Code: []int{61197}},
	PLZ{Name: "Frankenau", Code: []int{35110}},
	PLZ{Name: "Frankenberg", Code: []int{35066}},
	PLZ{Name: "Frankfurt Am Main", Code: []int{60306, 60308, 60310, 60311, 60313, 60314, 60316, 60318, 60320, 60322, 60323, 60325, 60326, 60327, 60329, 60385, 60386, 60388, 60389, 60431, 60433, 60435, 60437, 60438, 60439, 60486, 60487, 60488, 60489, 60528, 60529, 60549, 60594, 60596, 60598, 60599, 65929, 65931, 65933, 65934, 65936}},
	PLZ{Name: "Frankisch-Crumbach", Code: []int{64407}},
	PLZ{Name: "Freiensteinau", Code: []int{36399}},
	PLZ{Name: "Freigericht", Code: []int{63579}},
	PLZ{Name: "Friedberg", Code: []int{61169}},
	PLZ{Name: "Friedewald", Code: []int{36289}},
	PLZ{Name: "Friedrichsdorf", Code: []int{61381}},
	PLZ{Name: "Frielendorf", Code: []int{34621}},
	PLZ{Name: "Fritzlar", Code: []int{34560}},
	PLZ{Name: "Fronhausen", Code: []int{35112}},
	PLZ{Name: "Fulda", Code: []int{36037, 36039, 36041, 36043}},
	PLZ{Name: "Fuldabruck", Code: []int{34277}},
	PLZ{Name: "Fuldatal", Code: []int{34233}},
	PLZ{Name: "Furth", Code: []int{64658}},
	PLZ{Name: "Gedern", Code: []int{63688}},
	PLZ{Name: "Geisenheim", Code: []int{65366}},
	PLZ{Name: "Gelnhausen", Code: []int{63571}},
	PLZ{Name: "Gemunden", Code: []int{35285, 35329}},
	PLZ{Name: "Gernsheim", Code: []int{64579}},
	PLZ{Name: "Gersfeld", Code: []int{36129}},
	PLZ{Name: "Giesen", Code: []int{35390, 35392, 35394, 35396, 35398}},
	PLZ{Name: "Gilserberg", Code: []int{34630}},
	PLZ{Name: "Ginsheim-Gustavsburg", Code: []int{65462}},
	PLZ{Name: "Gladenbach", Code: []int{35075}},
	PLZ{Name: "Glashutten", Code: []int{61479}},
	PLZ{Name: "Glauburg", Code: []int{63695}},
	PLZ{Name: "Gorxheimertal", Code: []int{69517}},
	PLZ{Name: "Grasellenbach", Code: []int{64689}},
	PLZ{Name: "Gravenwiesbach", Code: []int{61279}},
	PLZ{Name: "Grebenau", Code: []int{36323}},
	PLZ{Name: "Grebenhain", Code: []int{36355}},
	PLZ{Name: "Grebenstein", Code: []int{34393}},
	PLZ{Name: "Greifenstein", Code: []int{35753}},
	PLZ{Name: "Griesheim", Code: []int{64347}},
	PLZ{Name: "Gros-Bieberau", Code: []int{64401}},
	PLZ{Name: "Gros-Gerau", Code: []int{64521}},
	PLZ{Name: "Gros-Rohrheim", Code: []int{68649}},
	PLZ{Name: "Gros-Umstadt", Code: []int{64823}},
	PLZ{Name: "Gros-Zimmern", Code: []int{64846}},
	PLZ{Name: "Grosalmerode", Code: []int{37247}},
	PLZ{Name: "Grosenluder", Code: []int{36137}},
	PLZ{Name: "Groskrotzenburg", Code: []int{63538}},
	PLZ{Name: "Grunberg", Code: []int{35305}},
	PLZ{Name: "Grundau", Code: []int{63584}},
	PLZ{Name: "Gudensberg", Code: []int{34281}},
	PLZ{Name: "Guxhagen", Code: []int{34302}},
	PLZ{Name: "Habichtswald", Code: []int{34317}},
	PLZ{Name: "Hadamar", Code: []int{65589}},
	PLZ{Name: "Haiger", Code: []int{35708}},
	PLZ{Name: "Haina", Code: []int{35114}},
	PLZ{Name: "Hainburg", Code: []int{63512}},
	PLZ{Name: "Hammersbach", Code: []int{63546}},
	PLZ{Name: "Hanau", Code: []int{63405, 63450, 63452, 63454, 63456, 63457}},
	PLZ{Name: "Hasselroth", Code: []int{63594}},
	PLZ{Name: "Hattersheim", Code: []int{65795}},
	PLZ{Name: "Hatzfeld", Code: []int{35116}},
	PLZ{Name: "Hauneck", Code: []int{36282}},
	PLZ{Name: "Haunetal", Code: []int{36166}},
	PLZ{Name: "Heidenrod", Code: []int{65321}},
	PLZ{Name: "Helsa", Code: []int{34298}},
	PLZ{Name: "Heppenheim", Code: []int{64646}},
	PLZ{Name: "Herborn", Code: []int{35745}},
	PLZ{Name: "Herbstein", Code: []int{36358}},
	PLZ{Name: "Heringen", Code: []int{36266}},
	PLZ{Name: "Herleshausen", Code: []int{37293}},
	PLZ{Name: "Hesseneck", Code: []int{64754}},
	PLZ{Name: "Hessisch Lichtenau", Code: []int{37235}},
	PLZ{Name: "Heuchelheim", Code: []int{35452}},
	PLZ{Name: "Heusenstamm", Code: []int{63150}},
	PLZ{Name: "Hilders", Code: []int{36115}},
	PLZ{Name: "Hirschhorn", Code: []int{69434}},
	PLZ{Name: "Hirzenhain", Code: []int{63697}},
	PLZ{Name: "Hochheim Am Main", Code: []int{65239}},
	PLZ{Name: "Hochst Im Odenwald", Code: []int{64739}},
	PLZ{Name: "Hofbieber", Code: []int{36145}},
	PLZ{Name: "Hofgeismar", Code: []int{34369}},
	PLZ{Name: "Hofheim Am Taunus", Code: []int{65719}},
	PLZ{Name: "Hohenahr", Code: []int{35644}},
	PLZ{Name: "Hohenroda", Code: []int{36284}},
	PLZ{Name: "Hohenstein", Code: []int{65329}},
	PLZ{Name: "Homberg", Code: []int{34576, 35315}},
	PLZ{Name: "Hosenfeld", Code: []int{36154}},
	PLZ{Name: "Hunfeld", Code: []int{36088}},
	PLZ{Name: "Hunfelden", Code: []int{65597}},
	PLZ{Name: "Hungen", Code: []int{35410}},
	PLZ{Name: "Hunstetten", Code: []int{65510}},
	PLZ{Name: "Huttenberg", Code: []int{35625}},
	PLZ{Name: "Idstein", Code: []int{65510}},
	PLZ{Name: "Immenhausen", Code: []int{34376}},
	PLZ{Name: "Jesberg", Code: []int{34632}},
	PLZ{Name: "Jossgrund", Code: []int{63637}},
	PLZ{Name: "Kalbach", Code: []int{36148}},
	PLZ{Name: "Karben", Code: []int{61184}},
	PLZ{Name: "Kassel", Code: []int{34117, 34119, 34121, 34123, 34125, 34127, 34128, 34130, 34131, 34132, 34134}},
	PLZ{Name: "Kaufungen", Code: []int{34260}},
	PLZ{Name: "Kefenrod", Code: []int{63699}},
	PLZ{Name: "Kelkheim", Code: []int{65779}},
	PLZ{Name: "Kelsterbach", Code: []int{65451}},
	PLZ{Name: "Kiedrich", Code: []int{65399}},
	PLZ{Name: "Kirchhain", Code: []int{35274}},
	PLZ{Name: "Kirchheim", Code: []int{36275}},
	PLZ{Name: "Kirtorf", Code: []int{36320}},
	PLZ{Name: "Knullwald", Code: []int{34593}},
	PLZ{Name: "Konigstein Im Taunus", Code: []int{61462}},
	PLZ{Name: "Konigstein Im Taunus Falkenstein", Code: []int{61462}},
	PLZ{Name: "Konigstein Im Taunus Mammolshain", Code: []int{61462}},
	PLZ{Name: "Konigstein Im Taunus Schneidhain", Code: []int{61462}},
	PLZ{Name: "Korbach", Code: []int{34497}},
	PLZ{Name: "Korle", Code: []int{34327}},
	PLZ{Name: "Kriftel", Code: []int{65830}},
	PLZ{Name: "Kronberg Im Taunus", Code: []int{61476}},
	PLZ{Name: "Kunzell", Code: []int{36093}},
	PLZ{Name: "Lahnau", Code: []int{35633}},
	PLZ{Name: "Lahntal", Code: []int{35094}},
	PLZ{Name: "Lampertheim", Code: []int{68623}},
	PLZ{Name: "Langen", Code: []int{63225}},
	PLZ{Name: "Langenselbold", Code: []int{63505}},
	PLZ{Name: "Langgons", Code: []int{35428}},
	PLZ{Name: "Laubach", Code: []int{35321}},
	PLZ{Name: "Lauterbach", Code: []int{36341}},
	PLZ{Name: "Lautertal", Code: []int{36369, 64686}},
	PLZ{Name: "Leun", Code: []int{35638}},
	PLZ{Name: "Lich", Code: []int{35423}},
	PLZ{Name: "Lichtenfels", Code: []int{35104}},
	PLZ{Name: "Liebenau", Code: []int{34396}},
	PLZ{Name: "Liederbach Am Taunus", Code: []int{65835}},
	PLZ{Name: "Limburg An Der Lahn", Code: []int{65549, 65550, 65551, 65552, 65553, 65554, 65555, 65556}},
	PLZ{Name: "Limeshain", Code: []int{63694}},
	PLZ{Name: "Linden", Code: []int{35440}},
	PLZ{Name: "Lindenfels", Code: []int{64678}},
	PLZ{Name: "Linsengericht", Code: []int{63589}},
	PLZ{Name: "Lohfelden", Code: []int{34253}},
	PLZ{Name: "Lohnberg", Code: []int{35792}},
	PLZ{Name: "Lohra", Code: []int{35102}},
	PLZ{Name: "Lollar", Code: []int{35457}},
	PLZ{Name: "Lorch", Code: []int{65391}},
	PLZ{Name: "Lorsch", Code: []int{64653}},
	PLZ{Name: "Ludwigsau", Code: []int{36251}},
	PLZ{Name: "Lutzelbach", Code: []int{64750}},
	PLZ{Name: "Mainhausen", Code: []int{63533}},
	PLZ{Name: "Maintal", Code: []int{63477}},
	PLZ{Name: "Mainz-Kastel", Code: []int{55252}},
	PLZ{Name: "Mainz-Kostheim", Code: []int{55246}},
	PLZ{Name: "Malsfeld", Code: []int{34323}},
	PLZ{Name: "Marburg", Code: []int{35037, 35039, 35041, 35043}},
	PLZ{Name: "Meinhard", Code: []int{37276}},
	PLZ{Name: "Meisner", Code: []int{37290}},
	PLZ{Name: "Melsungen", Code: []int{34212}},
	PLZ{Name: "Mengerskirchen", Code: []int{35794}},
	PLZ{Name: "Merenberg", Code: []int{35799}},
	PLZ{Name: "Messel", Code: []int{64409}},
	PLZ{Name: "Michelstadt", Code: []int{64720}},
	PLZ{Name: "Mittenaar", Code: []int{35756}},
	PLZ{Name: "Modautal", Code: []int{64397}},
	PLZ{Name: "Morfelden-Walldorf", Code: []int{64546}},
	PLZ{Name: "Morlenbach", Code: []int{69509}},
	PLZ{Name: "Morschen", Code: []int{34326}},
	PLZ{Name: "Mossautal", Code: []int{64756}},
	PLZ{Name: "Mucke", Code: []int{35325}},
	PLZ{Name: "Muhlheim", Code: []int{63165}},
	PLZ{Name: "Muhltal", Code: []int{64367}},
	PLZ{Name: "Munchhausen", Code: []int{35117}},
	PLZ{Name: "Munster", Code: []int{64839}},
	PLZ{Name: "Munzenberg", Code: []int{35516}},
	PLZ{Name: "Nauheim", Code: []int{64569}},
	PLZ{Name: "Naumburg", Code: []int{34311}},
	PLZ{Name: "Neckarsteinach", Code: []int{69239}},
	PLZ{Name: "Nentershausen", Code: []int{36214}},
	PLZ{Name: "Neu-Anspach", Code: []int{61267}},
	PLZ{Name: "Neu-Eichenberg", Code: []int{37249}},
	PLZ{Name: "Neu-Isenburg", Code: []int{63263}},
	PLZ{Name: "Neuberg", Code: []int{63543}},
	PLZ{Name: "Neuenstein", Code: []int{36286}},
	PLZ{Name: "Neuental", Code: []int{34599}},
	PLZ{Name: "Neuhof", Code: []int{36119}},
	PLZ{Name: "Neukirchen", Code: []int{34626}},
	PLZ{Name: "Neustadt", Code: []int{35279}},
	PLZ{Name: "Nidda", Code: []int{63667}},
	PLZ{Name: "Niddatal", Code: []int{61194}},
	PLZ{Name: "Nidderau", Code: []int{61130}},
	PLZ{Name: "Niedenstein", Code: []int{34305}},
	PLZ{Name: "Niederaula", Code: []int{36272}},
	PLZ{Name: "Niederdorfelden", Code: []int{61138}},
	PLZ{Name: "Niedernhausen", Code: []int{65527}},
	PLZ{Name: "Nieste", Code: []int{34329}},
	PLZ{Name: "Niestetal", Code: []int{34266}},
	PLZ{Name: "Nusttal", Code: []int{36167}},
	PLZ{Name: "Ober-Morlen", Code: []int{61239}},
	PLZ{Name: "Ober-Ramstadt", Code: []int{64372}},
	PLZ{Name: "Oberaula", Code: []int{36280}},
	PLZ{Name: "Obertshausen", Code: []int{63179}},
	PLZ{Name: "Oberursel", Code: []int{61440}},
	PLZ{Name: "Oberweser", Code: []int{34399}},
	PLZ{Name: "Oestrich-Winkel", Code: []int{65375}},
	PLZ{Name: "Offenbach", Code: []int{63065, 63067, 63069, 63071, 63073, 63075}},
	PLZ{Name: "Ortenberg", Code: []int{63683}},
	PLZ{Name: "Ottrau", Code: []int{34633}},
	PLZ{Name: "Otzberg", Code: []int{64853}},
	PLZ{Name: "Petersberg", Code: []int{36100}},
	PLZ{Name: "Pfungstadt", Code: []int{64319}},
	PLZ{Name: "Philippsthal", Code: []int{36269}},
	PLZ{Name: "Pohlheim", Code: []int{35415}},
	PLZ{Name: "Poppenhausen", Code: []int{36163}},
	PLZ{Name: "Rabenau", Code: []int{35466}},
	PLZ{Name: "Ranstadt", Code: []int{63691}},
	PLZ{Name: "Rasdorf", Code: []int{36169}},
	PLZ{Name: "Raunheim", Code: []int{65479}},
	PLZ{Name: "Rauschenberg", Code: []int{35282}},
	PLZ{Name: "Reichelsheim", Code: []int{61203, 64385}},
	PLZ{Name: "Reinhardshagen", Code: []int{34359}},
	PLZ{Name: "Reinheim", Code: []int{64354}},
	PLZ{Name: "Reiskirchen", Code: []int{35447}},
	PLZ{Name: "Riedstadt", Code: []int{64560}},
	PLZ{Name: "Rimbach", Code: []int{64668}},
	PLZ{Name: "Ringgau", Code: []int{37296}},
	PLZ{Name: "Rockenberg", Code: []int{35519}},
	PLZ{Name: "Rodenbach", Code: []int{63517}},
	PLZ{Name: "Rodermark", Code: []int{63322}},
	PLZ{Name: "Rodgau", Code: []int{63110}},
	PLZ{Name: "Romrod", Code: []int{36329}},
	PLZ{Name: "Ronneburg", Code: []int{63549}},
	PLZ{Name: "Ronshausen", Code: []int{36217}},
	PLZ{Name: "Rosbach Vor Der Hohe", Code: []int{61191}},
	PLZ{Name: "Rosbach Vor Der Hohe Nieder-Rosbach", Code: []int{61191}},
	PLZ{Name: "Rosbach Vor Der Hohe Ober-Rosbach", Code: []int{61191}},
	PLZ{Name: "Rosbach Vor Der Hohe Rodheim Vor Der Hohe", Code: []int{61191}},
	PLZ{Name: "Rosdorf", Code: []int{64380}},
	PLZ{Name: "Rosenthal", Code: []int{35119}},
	PLZ{Name: "Rotenburg An Der Fulda", Code: []int{36199}},
	PLZ{Name: "Rothenberg", Code: []int{64757}},
	PLZ{Name: "Rudesheim Am Rhein", Code: []int{65385}},
	PLZ{Name: "Runkel", Code: []int{65594}},
	PLZ{Name: "Russelsheim", Code: []int{65428}},
	PLZ{Name: "Schaafheim", Code: []int{64850}},
	PLZ{Name: "Schauenburg", Code: []int{34270}},
	PLZ{Name: "Schenklengsfeld", Code: []int{36277}},
	PLZ{Name: "Schlangenbad", Code: []int{65388}},
	PLZ{Name: "Schlitz", Code: []int{36110}},
	PLZ{Name: "Schluchtern", Code: []int{36381}},
	PLZ{Name: "Schmitten", Code: []int{61389}},
	PLZ{Name: "Schoffengrund", Code: []int{35641}},
	PLZ{Name: "Schoneck", Code: []int{61137}},
	PLZ{Name: "Schotten", Code: []int{63679}},
	PLZ{Name: "Schrecksbach", Code: []int{34637}},
	PLZ{Name: "Schwalbach Am Taunus", Code: []int{65824}},
	PLZ{Name: "Schwalmstadt", Code: []int{34613}},
	PLZ{Name: "Schwalmtal", Code: []int{36318}},
	PLZ{Name: "Schwarzenborn", Code: []int{34639}},
	PLZ{Name: "Seeheim-Jugenheim", Code: []int{64342}},
	PLZ{Name: "Seligenstadt", Code: []int{63500}},
	PLZ{Name: "Selters", Code: []int{65618}},
	PLZ{Name: "Siegbach", Code: []int{35768}},
	PLZ{Name: "Sinn", Code: []int{35764}},
	PLZ{Name: "Sinntal", Code: []int{36391}},
	PLZ{Name: "Sohrewald", Code: []int{34320}},
	PLZ{Name: "Solms", Code: []int{35606}},
	PLZ{Name: "Sontra", Code: []int{36205}},
	PLZ{Name: "Spangenberg", Code: []int{34286}},
	PLZ{Name: "Stadtallendorf", Code: []int{35260}},
	PLZ{Name: "Staufenberg", Code: []int{35460}},
	PLZ{Name: "Steffenberg", Code: []int{35239}},
	PLZ{Name: "Steinau An Der Strase", Code: []int{36396}},
	PLZ{Name: "Steinbach", Code: []int{61449}},
	PLZ{Name: "Stockstadt Am Rhein", Code: []int{64589}},
	PLZ{Name: "Sulzbach", Code: []int{65843}},
	PLZ{Name: "Tann", Code: []int{36142}},
	PLZ{Name: "Taunusstein", Code: []int{65219, 65220, 65221, 65222, 65223, 65224, 65232}},
	PLZ{Name: "Trebur", Code: []int{65468}},
	PLZ{Name: "Trendelburg", Code: []int{34388}},
	PLZ{Name: "Twistetal", Code: []int{34477}},
	PLZ{Name: "Ulrichstein", Code: []int{35327}},
	PLZ{Name: "Usingen", Code: []int{61250}},
	PLZ{Name: "Vellmar", Code: []int{34246}},
	PLZ{Name: "Viernheim", Code: []int{68519}},
	PLZ{Name: "Villmar", Code: []int{65606}},
	PLZ{Name: "Vohl", Code: []int{34516}},
	PLZ{Name: "Volkmarsen", Code: []int{34471}},
	PLZ{Name: "Wabern", Code: []int{34590}},
	PLZ{Name: "Wachtersbach", Code: []int{63607}},
	PLZ{Name: "Wald-Michelbach", Code: []int{69483}},
	PLZ{Name: "Waldbrunn", Code: []int{65620}},
	PLZ{Name: "Waldeck", Code: []int{34513}},
	PLZ{Name: "Waldems", Code: []int{65529}},
	PLZ{Name: "Waldkappel", Code: []int{37284}},
	PLZ{Name: "Waldsolms", Code: []int{35647}},
	PLZ{Name: "Walluf", Code: []int{65396}},
	PLZ{Name: "Wanfried", Code: []int{37281}},
	PLZ{Name: "Wartenberg", Code: []int{36367}},
	PLZ{Name: "Wehretal", Code: []int{37287}},
	PLZ{Name: "Wehrheim", Code: []int{61273}},
	PLZ{Name: "Weilburg", Code: []int{35781}},
	PLZ{Name: "Weilmunster", Code: []int{35789}},
	PLZ{Name: "Weilrod", Code: []int{61276}},
	PLZ{Name: "Weimar", Code: []int{35096}},
	PLZ{Name: "Weinbach", Code: []int{35796}},
	PLZ{Name: "Weisenborn", Code: []int{37299}},
	PLZ{Name: "Weiterstadt", Code: []int{64331}},
	PLZ{Name: "Wettenberg", Code: []int{35435}},
	PLZ{Name: "Wetter", Code: []int{35083}},
	PLZ{Name: "Wetzlar", Code: []int{35576, 35578, 35579, 35580, 35581, 35582, 35583, 35584, 35585, 35586}},
	PLZ{Name: "Wiesbaden", Code: []int{65183, 65185, 65187, 65189, 65191, 65193, 65195, 65197, 65199, 65201, 65203, 65205, 65207}},
	PLZ{Name: "Wildeck", Code: []int{36208}},
	PLZ{Name: "Willingen", Code: []int{34508}},
	PLZ{Name: "Willingshausen", Code: []int{34628}},
	PLZ{Name: "Witzenhausen", Code: []int{37213, 37214, 37215, 37216, 37217, 37218}},
	PLZ{Name: "Wohratal", Code: []int{35288}},
	PLZ{Name: "Wolfersheim", Code: []int{61200}},
	PLZ{Name: "Wolfhagen", Code: []int{34466}},
	PLZ{Name: "Wollstadt", Code: []int{61206}},
	PLZ{Name: "Zierenberg", Code: []int{34289}},
	PLZ{Name: "Zwingenberg", Code: []int{64673}},
}
