package plz

var sachsen_map = map[string]PLZ{
	"Adorf":                             PLZ{Name: "Adorf", Code: []int{8626}},
	"Altenberg":                         PLZ{Name: "Altenberg", Code: []int{1773}},
	"Altmittweida":                      PLZ{Name: "Altmittweida", Code: []int{9648}},
	"Amtsberg":                          PLZ{Name: "Amtsberg", Code: []int{9439}},
	"Annaberg-Buchholz":                 PLZ{Name: "Annaberg-Buchholz", Code: []int{9456}},
	"Arnsdorf":                          PLZ{Name: "Arnsdorf", Code: []int{1477}},
	"Arzberg":                           PLZ{Name: "Arzberg", Code: []int{4886}},
	"Aue":                               PLZ{Name: "Aue", Code: []int{8280}},
	"Auerbach":                          PLZ{Name: "Auerbach", Code: []int{9392}},
	"Auerbach/Vogtland":                 PLZ{Name: "Auerbach/Vogtland", Code: []int{8209}},
	"Augustusburg":                      PLZ{Name: "Augustusburg", Code: []int{9573}},
	"Bad Brambach":                      PLZ{Name: "Bad Brambach", Code: []int{8648}},
	"Bad Duben":                         PLZ{Name: "Bad Duben", Code: []int{4849}},
	"Bad Elster":                        PLZ{Name: "Bad Elster", Code: []int{8645}},
	"Bad Gottleuba-Berggieshubel":       PLZ{Name: "Bad Gottleuba-Berggieshubel", Code: []int{1816}},
	"Bad Lausick":                       PLZ{Name: "Bad Lausick", Code: []int{4651}},
	"Bad Muskau":                        PLZ{Name: "Bad Muskau", Code: []int{2953}},
	"Bad Schandau":                      PLZ{Name: "Bad Schandau", Code: []int{1814}},
	"Bahretal":                          PLZ{Name: "Bahretal", Code: []int{1819}},
	"Bannewitz":                         PLZ{Name: "Bannewitz", Code: []int{1728}},
	"Barenstein":                        PLZ{Name: "Barenstein", Code: []int{1768, 9471}},
	"Bautzen":                           PLZ{Name: "Bautzen", Code: []int{2625}},
	"Beierfeld":                         PLZ{Name: "Beierfeld", Code: []int{8340}},
	"Beiersdorf":                        PLZ{Name: "Beiersdorf", Code: []int{2736}},
	"Beilrode":                          PLZ{Name: "Beilrode", Code: []int{4886}},
	"Belgern":                           PLZ{Name: "Belgern", Code: []int{4874}},
	"Belgershain":                       PLZ{Name: "Belgershain", Code: []int{4683}},
	"Bennewitz":                         PLZ{Name: "Bennewitz", Code: []int{4828}},
	"Bergen":                            PLZ{Name: "Bergen", Code: []int{8239}},
	"Bernsbach":                         PLZ{Name: "Bernsbach", Code: []int{8315}},
	"Bernsdorf":                         PLZ{Name: "Bernsdorf", Code: []int{2994, 9337}},
	"Bernstadt Auf Dem Eigen":           PLZ{Name: "Bernstadt Auf Dem Eigen", Code: []int{2748}},
	"Berthelsdorf":                      PLZ{Name: "Berthelsdorf", Code: []int{2747}},
	"Bertsdorf-Hornitz":                 PLZ{Name: "Bertsdorf-Hornitz", Code: []int{2763}},
	"Beucha":                            PLZ{Name: "Beucha", Code: []int{4824}},
	"Bischofswerda":                     PLZ{Name: "Bischofswerda", Code: []int{1877}},
	"Bobritzsch":                        PLZ{Name: "Bobritzsch", Code: []int{9627}},
	"Bockau":                            PLZ{Name: "Bockau", Code: []int{8324}},
	"Bockelwitz":                        PLZ{Name: "Bockelwitz", Code: []int{4703}},
	"Bohlen":                            PLZ{Name: "Bohlen", Code: []int{4564}},
	"Borna":                             PLZ{Name: "Borna", Code: []int{4552}},
	"Bornichen/Erzgebirge":              PLZ{Name: "Bornichen/Erzgebirge", Code: []int{9437}},
	"Borsdorf":                          PLZ{Name: "Borsdorf", Code: []int{4451}},
	"Borstendorf":                       PLZ{Name: "Borstendorf", Code: []int{9579}},
	"Bosenbrunn":                        PLZ{Name: "Bosenbrunn", Code: []int{8606}},
	"Boxberg/Oberlausitz":               PLZ{Name: "Boxberg/Oberlausitz", Code: []int{2943}},
	"Brand-Erbisdorf":                   PLZ{Name: "Brand-Erbisdorf", Code: []int{9618}},
	"Brandis":                           PLZ{Name: "Brandis", Code: []int{4821}},
	"Breitenbrunn/Erzgebirge":           PLZ{Name: "Breitenbrunn/Erzgebirge", Code: []int{8359}},
	"Breitenfeld":                       PLZ{Name: "Breitenfeld", Code: []int{4158}},
	"Bretnig-Hauswalde":                 PLZ{Name: "Bretnig-Hauswalde", Code: []int{1900}},
	"Burghausen":                        PLZ{Name: "Burghausen", Code: []int{4178}},
	"Burgstadt":                         PLZ{Name: "Burgstadt", Code: []int{9217}},
	"Burgstein":                         PLZ{Name: "Burgstein", Code: []int{8538}},
	"Burkau":                            PLZ{Name: "Burkau", Code: []int{1906}},
	"Burkhardtsdorf":                    PLZ{Name: "Burkhardtsdorf", Code: []int{9235}},
	"Callenberg":                        PLZ{Name: "Callenberg", Code: []int{9337}},
	"Carlsfeld, Erzgebirge":             PLZ{Name: "Carlsfeld, Erzgebirge", Code: []int{8325}},
	"Cavertitz":                         PLZ{Name: "Cavertitz", Code: []int{4758}},
	"Chemnitz":                          PLZ{Name: "Chemnitz", Code: []int{9111, 9112, 9113, 9114, 9116, 9117, 9119, 9120, 9122, 9123, 9125, 9126, 9127, 9130, 9131}},
	"Chemnitz, Sachsen":                 PLZ{Name: "Chemnitz, Sachsen", Code: []int{9028, 9030, 9128}},
	"Clausnitz":                         PLZ{Name: "Clausnitz", Code: []int{9236}},
	"Colditz":                           PLZ{Name: "Colditz", Code: []int{4680}},
	"Coswig":                            PLZ{Name: "Coswig", Code: []int{1640}},
	"Crimmitschau":                      PLZ{Name: "Crimmitschau", Code: []int{8451}},
	"Crinitzberg":                       PLZ{Name: "Crinitzberg", Code: []int{8147}},
	"Crostau":                           PLZ{Name: "Crostau", Code: []int{2681}},
	"Crostwitz":                         PLZ{Name: "Crostwitz", Code: []int{1920}},
	"Crottendorf":                       PLZ{Name: "Crottendorf", Code: []int{9474}},
	"Cunewalde":                         PLZ{Name: "Cunewalde", Code: []int{2733}},
	"Dahlen":                            PLZ{Name: "Dahlen", Code: []int{4774}},
	"Delitzsch":                         PLZ{Name: "Delitzsch", Code: []int{4509}},
	"Demitz-Thumitz":                    PLZ{Name: "Demitz-Thumitz", Code: []int{1877}},
	"Dennheritz":                        PLZ{Name: "Dennheritz", Code: []int{8393}},
	"Deutschneudorf":                    PLZ{Name: "Deutschneudorf", Code: []int{9548}},
	"Deutzen":                           PLZ{Name: "Deutzen", Code: []int{4574}},
	"Diera-Zehren":                      PLZ{Name: "Diera-Zehren", Code: []int{1665}},
	"Diesbar-Seuslitz":                  PLZ{Name: "Diesbar-Seuslitz", Code: []int{1612}},
	"Dippoldiswalde":                    PLZ{Name: "Dippoldiswalde", Code: []int{1744}},
	"Dobeln":                            PLZ{Name: "Dobeln", Code: []int{4720}},
	"Dobernitz":                         PLZ{Name: "Dobernitz", Code: []int{4509}},
	"Doberschau-Gausig":                 PLZ{Name: "Doberschau-Gausig", Code: []int{1877, 2633, 2692}},
	"Doberschutz":                       PLZ{Name: "Doberschutz", Code: []int{4838}},
	"Dohma":                             PLZ{Name: "Dohma", Code: []int{1796}},
	"Dohna":                             PLZ{Name: "Dohna", Code: []int{1809}},
	"Dommitzsch":                        PLZ{Name: "Dommitzsch", Code: []int{4880}},
	"Dorfchemnitz Bei Sayda":            PLZ{Name: "Dorfchemnitz Bei Sayda", Code: []int{9619}},
	"Dorfhain":                          PLZ{Name: "Dorfhain", Code: []int{1738}},
	"Drebach":                           PLZ{Name: "Drebach", Code: []int{9430}},
	"Dreiheide":                         PLZ{Name: "Dreiheide", Code: []int{4860}},
	"Dresden":                           PLZ{Name: "Dresden", Code: []int{1067, 1069, 1097, 1099, 1108, 1109, 1127, 1129, 1139, 1156, 1157, 1159, 1169, 1187, 1189, 1217, 1219, 1237, 1239, 1257, 1259, 1277, 1279, 1307, 1309, 1324, 1326, 1328, 1465}},
	"Dresden Altfranken":                PLZ{Name: "Dresden Altfranken", Code: []int{1156}},
	"Dresden Blasewitz":                 PLZ{Name: "Dresden Blasewitz", Code: []int{1309}},
	"Dresden Friedrichstadt":            PLZ{Name: "Dresden Friedrichstadt", Code: []int{1067}},
	"Dresden Gompitz":                   PLZ{Name: "Dresden Gompitz", Code: []int{1156}},
	"Dresden Gompitz, Gompitz":          PLZ{Name: "Dresden Gompitz, Gompitz", Code: []int{1156}},
	"Dresden Gompitz, Ockerwitz":        PLZ{Name: "Dresden Gompitz, Ockerwitz", Code: []int{1156}},
	"Dresden Gompitz, Pennrich":         PLZ{Name: "Dresden Gompitz, Pennrich", Code: []int{1156}},
	"Dresden Gompitz, Roitzsch":         PLZ{Name: "Dresden Gompitz, Roitzsch", Code: []int{1156}},
	"Dresden Gompitz, Steinbach":        PLZ{Name: "Dresden Gompitz, Steinbach", Code: []int{1156}},
	"Dresden Gompitz, Unkersdorf":       PLZ{Name: "Dresden Gompitz, Unkersdorf", Code: []int{1156}},
	"Dresden Gompitz, Zollmen":          PLZ{Name: "Dresden Gompitz, Zollmen", Code: []int{1156}},
	"Dresden Innere Altstadt":           PLZ{Name: "Dresden Innere Altstadt", Code: []int{1067}},
	"Dresden Langebruck":                PLZ{Name: "Dresden Langebruck", Code: []int{1465}},
	"Dresden Striesen":                  PLZ{Name: "Dresden Striesen", Code: []int{1277}},
	"Dresden Tolkewitz":                 PLZ{Name: "Dresden Tolkewitz", Code: []int{1277, 1279}},
	"Durrhennersdorf":                   PLZ{Name: "Durrhennersdorf", Code: []int{2708}},
	"Durrrohrsdorf-Dittersbach":         PLZ{Name: "Durrrohrsdorf-Dittersbach", Code: []int{1833}},
	"Ebersbach":                         PLZ{Name: "Ebersbach", Code: []int{1561, 4720}},
	"Ebersbach/Sachsen":                 PLZ{Name: "Ebersbach/Sachsen", Code: []int{2730}},
	"Ehrenfriedersdorf":                 PLZ{Name: "Ehrenfriedersdorf", Code: []int{9427}},
	"Eibau":                             PLZ{Name: "Eibau", Code: []int{2739}},
	"Eibenstock":                        PLZ{Name: "Eibenstock", Code: []int{8309}},
	"Eichigt":                           PLZ{Name: "Eichigt", Code: []int{8626}},
	"Eilenburg":                         PLZ{Name: "Eilenburg", Code: []int{4838}},
	"Einsiedel Bei Chemnitz":            PLZ{Name: "Einsiedel Bei Chemnitz", Code: []int{9227}},
	"Ellefeld":                          PLZ{Name: "Ellefeld", Code: []int{8236}},
	"Elsnig":                            PLZ{Name: "Elsnig", Code: []int{4880}},
	"Elsterberg":                        PLZ{Name: "Elsterberg", Code: []int{7985}},
	"Elsterheide":                       PLZ{Name: "Elsterheide", Code: []int{2979, 2991}},
	"Elstertrebnitz":                    PLZ{Name: "Elstertrebnitz", Code: []int{4523}},
	"Elstra":                            PLZ{Name: "Elstra", Code: []int{1920}},
	"Elterlein":                         PLZ{Name: "Elterlein", Code: []int{9481}},
	"Eppendorf":                         PLZ{Name: "Eppendorf", Code: []int{9575}},
	"Erlabrunn":                         PLZ{Name: "Erlabrunn", Code: []int{8349}},
	"Erlau":                             PLZ{Name: "Erlau", Code: []int{9306}},
	"Erlbach":                           PLZ{Name: "Erlbach", Code: []int{8265}},
	"Erlbach-Kirchberg":                 PLZ{Name: "Erlbach-Kirchberg", Code: []int{9385}},
	"Espenhain":                         PLZ{Name: "Espenhain", Code: []int{4579}},
	"Eulatal":                           PLZ{Name: "Eulatal", Code: []int{4651}},
	"Eulowitz":                          PLZ{Name: "Eulowitz", Code: []int{2692}},
	"Falkenau":                          PLZ{Name: "Falkenau", Code: []int{9569}},
	"Falkenhain":                        PLZ{Name: "Falkenhain", Code: []int{4808}},
	"Falkenstein/Vogtland":              PLZ{Name: "Falkenstein/Vogtland", Code: []int{8223}},
	"Floha":                             PLZ{Name: "Floha", Code: []int{9557}},
	"Frankenberg/Sachsen":               PLZ{Name: "Frankenberg/Sachsen", Code: []int{9669}},
	"Frankenstein":                      PLZ{Name: "Frankenstein", Code: []int{9569}},
	"Frankenthal":                       PLZ{Name: "Frankenthal", Code: []int{1909}},
	"Frauenstein":                       PLZ{Name: "Frauenstein", Code: []int{9623}},
	"Fraureuth":                         PLZ{Name: "Fraureuth", Code: []int{8427}},
	"Freiberg":                          PLZ{Name: "Freiberg", Code: []int{9599}},
	"Freital":                           PLZ{Name: "Freital", Code: []int{1705}},
	"Friedersdorf":                      PLZ{Name: "Friedersdorf", Code: []int{2742}},
	"Frohburg":                          PLZ{Name: "Frohburg", Code: []int{4654}},
	"Gablenz":                           PLZ{Name: "Gablenz", Code: []int{2953}},
	"Gahlenz":                           PLZ{Name: "Gahlenz", Code: []int{9569}},
	"Geising":                           PLZ{Name: "Geising", Code: []int{1778}},
	"Geithain":                          PLZ{Name: "Geithain", Code: []int{4643}},
	"Gelenau/Erzgebirge":                PLZ{Name: "Gelenau/Erzgebirge", Code: []int{9423}},
	"Geringswalde":                      PLZ{Name: "Geringswalde", Code: []int{9326}},
	"Gersdorf":                          PLZ{Name: "Gersdorf", Code: []int{4703, 9355}},
	"Geyer":                             PLZ{Name: "Geyer", Code: []int{9468}},
	"Glashutte":                         PLZ{Name: "Glashutte", Code: []int{1768}},
	"Glaubitz":                          PLZ{Name: "Glaubitz", Code: []int{1612}},
	"Glauchau":                          PLZ{Name: "Glauchau", Code: []int{8371}},
	"Goda":                              PLZ{Name: "Goda", Code: []int{2633}},
	"Gohrisch":                          PLZ{Name: "Gohrisch", Code: []int{1824}},
	"Gorlitz":                           PLZ{Name: "Gorlitz", Code: []int{2826, 2827, 2828}},
	"Gornau/Erzgebirge":                 PLZ{Name: "Gornau/Erzgebirge", Code: []int{9405}},
	"Gornsdorf":                         PLZ{Name: "Gornsdorf", Code: []int{9390}},
	"Grimma":                            PLZ{Name: "Grimma", Code: []int{4668}},
	"Groditz":                           PLZ{Name: "Groditz", Code: []int{1609}},
	"Groitzsch":                         PLZ{Name: "Groitzsch", Code: []int{4539}},
	"Gros Duben":                        PLZ{Name: "Gros Duben", Code: []int{2959}},
	"Grosbardau":                        PLZ{Name: "Grosbardau", Code: []int{4668}},
	"Grosbothen":                        PLZ{Name: "Grosbothen", Code: []int{4668}},
	"Grosdubrau":                        PLZ{Name: "Grosdubrau", Code: []int{2694}},
	"Grosenhain":                        PLZ{Name: "Grosenhain", Code: []int{1558}},
	"Grosharthau":                       PLZ{Name: "Grosharthau", Code: []int{1909}},
	"Groshartmannsdorf":                 PLZ{Name: "Groshartmannsdorf", Code: []int{9618}},
	"Groshennersdorf":                   PLZ{Name: "Groshennersdorf", Code: []int{2747}},
	"Groslehna":                         PLZ{Name: "Groslehna", Code: []int{4420}},
	"Grosnaundorf":                      PLZ{Name: "Grosnaundorf", Code: []int{1936}},
	"Grosolbersdorf":                    PLZ{Name: "Grosolbersdorf", Code: []int{9432}},
	"Grosposna":                         PLZ{Name: "Grosposna", Code: []int{4463}},
	"Grospostwitz/Oberlausitz":          PLZ{Name: "Grospostwitz/Oberlausitz", Code: []int{2692}},
	"Grosrohrsdorf":                     PLZ{Name: "Grosrohrsdorf", Code: []int{1900}},
	"Grosruckerswalde":                  PLZ{Name: "Grosruckerswalde", Code: []int{9518}},
	"Grosschirma":                       PLZ{Name: "Grosschirma", Code: []int{9603}},
	"Grosschonau":                       PLZ{Name: "Grosschonau", Code: []int{2779}},
	"Grosschweidnitz":                   PLZ{Name: "Grosschweidnitz", Code: []int{2708}},
	"Grostreben-Zwethau":                PLZ{Name: "Grostreben-Zwethau", Code: []int{4886}},
	"Grosweitzschen":                    PLZ{Name: "Grosweitzschen", Code: []int{4720}},
	"Grunbach":                          PLZ{Name: "Grunbach", Code: []int{8223}},
	"Grunhain":                          PLZ{Name: "Grunhain", Code: []int{8344}},
	"Grunhainichen":                     PLZ{Name: "Grunhainichen", Code: []int{9579}},
	"Guttau":                            PLZ{Name: "Guttau", Code: []int{2694}},
	"Hahnichen":                         PLZ{Name: "Hahnichen", Code: []int{2923}},
	"Hainewalde":                        PLZ{Name: "Hainewalde", Code: []int{2779}},
	"Hainichen":                         PLZ{Name: "Hainichen", Code: []int{9661}},
	"Halsbrucke":                        PLZ{Name: "Halsbrucke", Code: []int{9633}},
	"Hammerbrucke":                      PLZ{Name: "Hammerbrucke", Code: []int{8269}},
	"Hartenstein":                       PLZ{Name: "Hartenstein", Code: []int{8118}},
	"Hartenstein Hartenstein":           PLZ{Name: "Hartenstein Hartenstein", Code: []int{8118}},
	"Hartenstein Thierfeld":             PLZ{Name: "Hartenstein Thierfeld", Code: []int{8118}},
	"Hartenstein Zschocken":             PLZ{Name: "Hartenstein Zschocken", Code: []int{8118}},
	"Hartha":                            PLZ{Name: "Hartha", Code: []int{4746}},
	"Hartmannsdorf":                     PLZ{Name: "Hartmannsdorf", Code: []int{9232}},
	"Hartmannsdorf Bei Kirchberg":       PLZ{Name: "Hartmannsdorf Bei Kirchberg", Code: []int{8107}},
	"Hartmannsdorf-Reichenau":           PLZ{Name: "Hartmannsdorf-Reichenau", Code: []int{1762}},
	"Haselbachtal":                      PLZ{Name: "Haselbachtal", Code: []int{1920, 1936}},
	"Heidenau":                          PLZ{Name: "Heidenau", Code: []int{1809}},
	"Heidersdorf":                       PLZ{Name: "Heidersdorf", Code: []int{9526}},
	"Heinsdorfergrund":                  PLZ{Name: "Heinsdorfergrund", Code: []int{8468}},
	"Hellerau":                          PLZ{Name: "Hellerau", Code: []int{1109}},
	"Hermsdorf/Erzgebirge":              PLZ{Name: "Hermsdorf/Erzgebirge", Code: []int{1776}},
	"Herrnhut":                          PLZ{Name: "Herrnhut", Code: []int{2747}},
	"Heuersdorf":                        PLZ{Name: "Heuersdorf", Code: []int{4574}},
	"Heynitz":                           PLZ{Name: "Heynitz", Code: []int{1683}},
	"Hilbersdorf":                       PLZ{Name: "Hilbersdorf", Code: []int{9627}},
	"Hirschfeld":                        PLZ{Name: "Hirschfeld", Code: []int{8107, 8144}},
	"Hirschfelde":                       PLZ{Name: "Hirschfelde", Code: []int{2788}},
	"Hirschfelde Dittelsdorf":           PLZ{Name: "Hirschfelde Dittelsdorf", Code: []int{2788}},
	"Hirschstein":                       PLZ{Name: "Hirschstein", Code: []int{1594}},
	"Hochkirch":                         PLZ{Name: "Hochkirch", Code: []int{2627}},
	"Hockendorf":                        PLZ{Name: "Hockendorf", Code: []int{1774}},
	"Hohburg":                           PLZ{Name: "Hohburg", Code: []int{4808}},
	"Hohendubrau":                       PLZ{Name: "Hohendubrau", Code: []int{2906}},
	"Hohenstein-Ernstthal":              PLZ{Name: "Hohenstein-Ernstthal", Code: []int{9337}},
	"Hohndorf":                          PLZ{Name: "Hohndorf", Code: []int{9394}},
	"Hohnstein":                         PLZ{Name: "Hohnstein", Code: []int{1848}},
	"Hohwald":                           PLZ{Name: "Hohwald", Code: []int{1844}},
	"Horka":                             PLZ{Name: "Horka", Code: []int{2923}},
	"Hormersdorf":                       PLZ{Name: "Hormersdorf", Code: []int{9395}},
	"Hoyerswerda":                       PLZ{Name: "Hoyerswerda", Code: []int{2977}},
	"Hundshubel":                        PLZ{Name: "Hundshubel", Code: []int{8318}},
	"Jahnsdorf/Erzgebirge":              PLZ{Name: "Jahnsdorf/Erzgebirge", Code: []int{9387}},
	"Jesewitz":                          PLZ{Name: "Jesewitz", Code: []int{4838}},
	"Johanngeorgenstadt":                PLZ{Name: "Johanngeorgenstadt", Code: []int{8349}},
	"Johstadt":                          PLZ{Name: "Johstadt", Code: []int{9477}},
	"Jonsdorf":                          PLZ{Name: "Jonsdorf", Code: []int{2796}},
	"Josnitz":                           PLZ{Name: "Josnitz", Code: []int{8547}},
	"Kabschutztal":                      PLZ{Name: "Kabschutztal", Code: []int{1665}},
	"Kamenz":                            PLZ{Name: "Kamenz", Code: []int{1917}},
	"Kandler":                           PLZ{Name: "Kandler", Code: []int{9212}},
	"Ketzerbachtal":                     PLZ{Name: "Ketzerbachtal", Code: []int{1623}},
	"Kirchberg":                         PLZ{Name: "Kirchberg", Code: []int{8107}},
	"Kirnitzschtal":                     PLZ{Name: "Kirnitzschtal", Code: []int{1855}},
	"Kirschau":                          PLZ{Name: "Kirschau", Code: []int{2681}},
	"Kittlitz":                          PLZ{Name: "Kittlitz", Code: []int{2708}},
	"Kitzen":                            PLZ{Name: "Kitzen", Code: []int{4460}},
	"Kitzscher":                         PLZ{Name: "Kitzscher", Code: []int{4567}},
	"Klingenthal/Sachsen":               PLZ{Name: "Klingenthal/Sachsen", Code: []int{8248}},
	"Klipphausen":                       PLZ{Name: "Klipphausen", Code: []int{1665}},
	"Klitten":                           PLZ{Name: "Klitten", Code: []int{2906}},
	"Klotzsche":                         PLZ{Name: "Klotzsche", Code: []int{1109}},
	"Knappensee":                        PLZ{Name: "Knappensee", Code: []int{2999}},
	"Kodersdorf":                        PLZ{Name: "Kodersdorf", Code: []int{2923}},
	"Kohren-Sahlis":                     PLZ{Name: "Kohren-Sahlis", Code: []int{4655}},
	"Konigsbruck":                       PLZ{Name: "Konigsbruck", Code: []int{1936}},
	"Konigsfeld":                        PLZ{Name: "Konigsfeld", Code: []int{9306}},
	"Konigshain":                        PLZ{Name: "Konigshain", Code: []int{2829}},
	"Konigshain-Wiederau":               PLZ{Name: "Konigshain-Wiederau", Code: []int{9306}},
	"Konigstein/Sachsische Schweiz":     PLZ{Name: "Konigstein/Sachsische Schweiz", Code: []int{1824}},
	"Konigswalde":                       PLZ{Name: "Konigswalde", Code: []int{9471}},
	"Konigswartha":                      PLZ{Name: "Konigswartha", Code: []int{2699}},
	"Kossa":                             PLZ{Name: "Kossa", Code: []int{4849}},
	"Krauschwitz":                       PLZ{Name: "Krauschwitz", Code: []int{2957}},
	"Kreba-Neudorf":                     PLZ{Name: "Kreba-Neudorf", Code: []int{2906}},
	"Kreischa":                          PLZ{Name: "Kreischa", Code: []int{1731}},
	"Kriebstein":                        PLZ{Name: "Kriebstein", Code: []int{9648}},
	"Krostitz":                          PLZ{Name: "Krostitz", Code: []int{4509}},
	"Kubschutz":                         PLZ{Name: "Kubschutz", Code: []int{2627}},
	"Kuhren-Burkartshain":               PLZ{Name: "Kuhren-Burkartshain", Code: []int{4808}},
	"Lampertswalde":                     PLZ{Name: "Lampertswalde", Code: []int{1561}},
	"Langenbernsdorf":                   PLZ{Name: "Langenbernsdorf", Code: []int{8428}},
	"Langenhessen":                      PLZ{Name: "Langenhessen", Code: []int{8439}},
	"Langenweisbach":                    PLZ{Name: "Langenweisbach", Code: []int{8134}},
	"Langenweisbach Grunau":             PLZ{Name: "Langenweisbach Grunau", Code: []int{8134}},
	"Langenweisbach Langenbach":         PLZ{Name: "Langenweisbach Langenbach", Code: []int{8134}},
	"Langenweisbach Weisbach":           PLZ{Name: "Langenweisbach Weisbach", Code: []int{8134}},
	"Lausig":                            PLZ{Name: "Lausig", Code: []int{4838}},
	"Lausnitz":                          PLZ{Name: "Lausnitz", Code: []int{1936}},
	"Lauta":                             PLZ{Name: "Lauta", Code: []int{2991}},
	"Lauter/Sachsen":                    PLZ{Name: "Lauter/Sachsen", Code: []int{8312}},
	"Lawalde":                           PLZ{Name: "Lawalde", Code: []int{2708}},
	"Leippe-Torno":                      PLZ{Name: "Leippe-Torno", Code: []int{2991}},
	"Leipzig":                           PLZ{Name: "Leipzig", Code: []int{4103, 4105, 4107, 4109, 4129, 4155, 4157, 4159, 4177, 4179, 4205, 4207, 4209, 4229, 4249, 4275, 4277, 4279, 4288, 4289, 4299, 4315, 4316, 4317, 4318, 4319, 4329, 4347, 4349, 4356, 4357}},
	"Leisnig":                           PLZ{Name: "Leisnig", Code: []int{4703}},
	"Lengefeld":                         PLZ{Name: "Lengefeld", Code: []int{9514}},
	"Lengenfeld":                        PLZ{Name: "Lengenfeld", Code: []int{8485}},
	"Leuben-Schleinitz":                 PLZ{Name: "Leuben-Schleinitz", Code: []int{1623}},
	"Leubnitz":                          PLZ{Name: "Leubnitz", Code: []int{8412}},
	"Leubsdorf":                         PLZ{Name: "Leubsdorf", Code: []int{9573}},
	"Leutersdorf":                       PLZ{Name: "Leutersdorf", Code: []int{2794}},
	"Lichtenau":                         PLZ{Name: "Lichtenau", Code: []int{9244}},
	"Lichtenberg":                       PLZ{Name: "Lichtenberg", Code: []int{1896}},
	"Lichtenberg/Erzgebirge":            PLZ{Name: "Lichtenberg/Erzgebirge", Code: []int{9638}},
	"Lichtenstein/Sachsen":              PLZ{Name: "Lichtenstein/Sachsen", Code: []int{9350}},
	"Lichtentanne":                      PLZ{Name: "Lichtentanne", Code: []int{8115}},
	"Liebschutzberg":                    PLZ{Name: "Liebschutzberg", Code: []int{4758}},
	"Liebstadt":                         PLZ{Name: "Liebstadt", Code: []int{1825}},
	"Limbach":                           PLZ{Name: "Limbach", Code: []int{8491}},
	"Limbach-Oberfrohna":                PLZ{Name: "Limbach-Oberfrohna", Code: []int{9212}},
	"Lobau":                             PLZ{Name: "Lobau", Code: []int{2708}},
	"Lobnitz":                           PLZ{Name: "Lobnitz", Code: []int{4509}},
	"Lobstadt":                          PLZ{Name: "Lobstadt", Code: []int{4552}},
	"Lohmen":                            PLZ{Name: "Lohmen", Code: []int{1847}},
	"Lohsa":                             PLZ{Name: "Lohsa", Code: []int{2999}},
	"Lommatzsch":                        PLZ{Name: "Lommatzsch", Code: []int{1623}},
	"Losnitz":                           PLZ{Name: "Losnitz", Code: []int{8294}},
	"Lugau/Erzgebirge":                  PLZ{Name: "Lugau/Erzgebirge", Code: []int{9385}},
	"Lunzenau":                          PLZ{Name: "Lunzenau", Code: []int{9328}},
	"Machern":                           PLZ{Name: "Machern", Code: []int{4827}},
	"Malschwitz":                        PLZ{Name: "Malschwitz", Code: []int{2694}},
	"Marienberg":                        PLZ{Name: "Marienberg", Code: []int{9496}},
	"Markersbach":                       PLZ{Name: "Markersbach", Code: []int{8352}},
	"Markersdorf":                       PLZ{Name: "Markersdorf", Code: []int{2829}},
	"Markkleeberg":                      PLZ{Name: "Markkleeberg", Code: []int{4416}},
	"Markneukirchen":                    PLZ{Name: "Markneukirchen", Code: []int{8258}},
	"Markranstadt":                      PLZ{Name: "Markranstadt", Code: []int{4420}},
	"Marsdorf":                          PLZ{Name: "Marsdorf", Code: []int{1108}},
	"Meerane":                           PLZ{Name: "Meerane", Code: []int{8393}},
	"Mehltheuer":                        PLZ{Name: "Mehltheuer", Code: []int{8539}},
	"Meisen":                            PLZ{Name: "Meisen", Code: []int{1662}},
	"Mildenau":                          PLZ{Name: "Mildenau", Code: []int{9456}},
	"Mittelbach Bei Chemnitz":           PLZ{Name: "Mittelbach Bei Chemnitz", Code: []int{9224}},
	"Mittelherwigsdorf":                 PLZ{Name: "Mittelherwigsdorf", Code: []int{2763}},
	"Mittweida":                         PLZ{Name: "Mittweida", Code: []int{9648}},
	"Mochau":                            PLZ{Name: "Mochau", Code: []int{4720}},
	"Mockrehna":                         PLZ{Name: "Mockrehna", Code: []int{4838, 4862}},
	"Morgenrothe-Rautenkranz":           PLZ{Name: "Morgenrothe-Rautenkranz", Code: []int{8262}},
	"Moritzburg":                        PLZ{Name: "Moritzburg", Code: []int{1468}},
	"Mucka":                             PLZ{Name: "Mucka", Code: []int{2906}},
	"Mugeln":                            PLZ{Name: "Mugeln", Code: []int{4769}},
	"Muglitztal":                        PLZ{Name: "Muglitztal", Code: []int{1809}},
	"Muhlau":                            PLZ{Name: "Muhlau", Code: []int{9241}},
	"Muhlental":                         PLZ{Name: "Muhlental", Code: []int{8606}},
	"Muhltroff":                         PLZ{Name: "Muhltroff", Code: []int{7919}},
	"Mulda/Sachsen":                     PLZ{Name: "Mulda/Sachsen", Code: []int{9619}},
	"Mulsen":                            PLZ{Name: "Mulsen", Code: []int{8132}},
	"Mulsen Mulsen Sankt Jacob":         PLZ{Name: "Mulsen Mulsen Sankt Jacob", Code: []int{8132}},
	"Mulsen Mulsen Sankt Micheln":       PLZ{Name: "Mulsen Mulsen Sankt Micheln", Code: []int{8132}},
	"Mulsen Mulsen Sankt Niclas":        PLZ{Name: "Mulsen Mulsen Sankt Niclas", Code: []int{8132}},
	"Mulsen Niedermulsen":               PLZ{Name: "Mulsen Niedermulsen", Code: []int{8132}},
	"Mulsen Ortmannsdorf":               PLZ{Name: "Mulsen Ortmannsdorf", Code: []int{8132}},
	"Mulsen Ortmannsdorf, Marienau":     PLZ{Name: "Mulsen Ortmannsdorf, Marienau", Code: []int{8132}},
	"Mulsen Ortmannsdorf, Neuschonburg": PLZ{Name: "Mulsen Ortmannsdorf, Neuschonburg", Code: []int{8132}},
	"Mulsen Ortmannsdorf, Ortmannsdorf": PLZ{Name: "Mulsen Ortmannsdorf, Ortmannsdorf", Code: []int{8132}},
	"Mulsen Stangendorf":                PLZ{Name: "Mulsen Stangendorf", Code: []int{8132}},
	"Mulsen Thurm":                      PLZ{Name: "Mulsen Thurm", Code: []int{8132}},
	"Mulsen Wulm":                       PLZ{Name: "Mulsen Wulm", Code: []int{8132}},
	"Mulsen Wulm, Bertelsdorf":          PLZ{Name: "Mulsen Wulm, Bertelsdorf", Code: []int{8132}},
	"Mulsen Wulm, Wulm":                 PLZ{Name: "Mulsen Wulm, Wulm", Code: []int{8132}},
	"Mutzschen":                         PLZ{Name: "Mutzschen", Code: []int{4688}},
	"Mylau":                             PLZ{Name: "Mylau", Code: []int{8499}},
	"Narsdorf":                          PLZ{Name: "Narsdorf", Code: []int{4657}},
	"Naundorf":                          PLZ{Name: "Naundorf", Code: []int{4769}},
	"Naunhof":                           PLZ{Name: "Naunhof", Code: []int{4683}},
	"Nauwalde":                          PLZ{Name: "Nauwalde", Code: []int{1609}},
	"Nebelschutz":                       PLZ{Name: "Nebelschutz", Code: []int{1920}},
	"Neiseaue":                          PLZ{Name: "Neiseaue", Code: []int{2829, 2923}},
	"Nerchau":                           PLZ{Name: "Nerchau", Code: []int{4685}},
	"Neschwitz":                         PLZ{Name: "Neschwitz", Code: []int{2699}},
	"Netzschkau":                        PLZ{Name: "Netzschkau", Code: []int{8491}},
	"Neuensalz":                         PLZ{Name: "Neuensalz", Code: []int{8541}},
	"Neugersdorf":                       PLZ{Name: "Neugersdorf", Code: []int{2727}},
	"Neuhausen/Erzgebirge":              PLZ{Name: "Neuhausen/Erzgebirge", Code: []int{9544}},
	"Neukieritzsch":                     PLZ{Name: "Neukieritzsch", Code: []int{4575}},
	"Neukirch":                          PLZ{Name: "Neukirch", Code: []int{1936}},
	"Neukirch/Lausitz":                  PLZ{Name: "Neukirch/Lausitz", Code: []int{1904}},
	"Neukirchen/Erzgebirge":             PLZ{Name: "Neukirchen/Erzgebirge", Code: []int{9221}},
	"Neukirchen/Pleise":                 PLZ{Name: "Neukirchen/Pleise", Code: []int{8459}},
	"Neukyhna":                          PLZ{Name: "Neukyhna", Code: []int{4509}},
	"Neumark":                           PLZ{Name: "Neumark", Code: []int{8496}},
	"Neusalza-Spremberg":                PLZ{Name: "Neusalza-Spremberg", Code: []int{2742}},
	"Neustadt In Sachsen":               PLZ{Name: "Neustadt In Sachsen", Code: []int{1844}},
	"Neustadt/Vogtland":                 PLZ{Name: "Neustadt/Vogtland", Code: []int{8223}},
	"Niederau":                          PLZ{Name: "Niederau", Code: []int{1689}},
	"Niedercunnersdorf":                 PLZ{Name: "Niedercunnersdorf", Code: []int{2708}},
	"Niederdorf":                        PLZ{Name: "Niederdorf", Code: []int{9366}},
	"Niederfrohna":                      PLZ{Name: "Niederfrohna", Code: []int{9243}},
	"Niederschona":                      PLZ{Name: "Niederschona", Code: []int{9600}},
	"Niederstriegis":                    PLZ{Name: "Niederstriegis", Code: []int{4741}},
	"Niederwiesa":                       PLZ{Name: "Niederwiesa", Code: []int{9577}},
	"Niederwurschnitz":                  PLZ{Name: "Niederwurschnitz", Code: []int{9399}},
	"Niesky":                            PLZ{Name: "Niesky", Code: []int{2906}},
	"Nossen":                            PLZ{Name: "Nossen", Code: []int{1683}},
	"Nunchritz":                         PLZ{Name: "Nunchritz", Code: []int{1612}},
	"Obercunnersdorf":                   PLZ{Name: "Obercunnersdorf", Code: []int{2708}},
	"Obergurig":                         PLZ{Name: "Obergurig", Code: []int{2692}},
	"Oberlichtenau":                     PLZ{Name: "Oberlichtenau", Code: []int{1936}},
	"Oberlungwitz":                      PLZ{Name: "Oberlungwitz", Code: []int{9353}},
	"Oberschona":                        PLZ{Name: "Oberschona", Code: []int{9600}},
	"Oberwiera":                         PLZ{Name: "Oberwiera", Code: []int{8396}},
	"Oberwiesenthal":                    PLZ{Name: "Oberwiesenthal", Code: []int{9484}},
	"Oderwitz":                          PLZ{Name: "Oderwitz", Code: []int{2791}},
	"Oederan":                           PLZ{Name: "Oederan", Code: []int{9569}},
	"Oelsnitz":                          PLZ{Name: "Oelsnitz", Code: []int{8606}},
	"Oelsnitz/Erzgebirge":               PLZ{Name: "Oelsnitz/Erzgebirge", Code: []int{9376}},
	"Ohorn":                             PLZ{Name: "Ohorn", Code: []int{1896}},
	"Olbernhau":                         PLZ{Name: "Olbernhau", Code: []int{9526}},
	"Olbersdorf":                        PLZ{Name: "Olbersdorf", Code: []int{2785}},
	"Oppach":                            PLZ{Name: "Oppach", Code: []int{2736}},
	"Oschatz":                           PLZ{Name: "Oschatz", Code: []int{4758}},
	"Osling":                            PLZ{Name: "Osling", Code: []int{1920}},
	"Ostrau":                            PLZ{Name: "Ostrau", Code: []int{4749}},
	"Ostritz":                           PLZ{Name: "Ostritz", Code: []int{2899}},
	"Ottendorf-Okrilla":                 PLZ{Name: "Ottendorf-Okrilla", Code: []int{1458}},
	"Otterwisch":                        PLZ{Name: "Otterwisch", Code: []int{4668}},
	"Oybin":                             PLZ{Name: "Oybin", Code: []int{2797}},
	"Panschwitz-Kuckau":                 PLZ{Name: "Panschwitz-Kuckau", Code: []int{1920}},
	"Parthenstein":                      PLZ{Name: "Parthenstein", Code: []int{4668}},
	"Pausa":                             PLZ{Name: "Pausa", Code: []int{7952}},
	"Pegau":                             PLZ{Name: "Pegau", Code: []int{4523}},
	"Penig":                             PLZ{Name: "Penig", Code: []int{9322}},
	"Pfaffroda":                         PLZ{Name: "Pfaffroda", Code: []int{9526}},
	"Pfluckuff":                         PLZ{Name: "Pfluckuff", Code: []int{4860}},
	"Pirna":                             PLZ{Name: "Pirna", Code: []int{1796}},
	"Plauen":                            PLZ{Name: "Plauen", Code: []int{8523, 8525, 8527, 8529}},
	"Pleisa":                            PLZ{Name: "Pleisa", Code: []int{9212}},
	"Pobershau":                         PLZ{Name: "Pobershau", Code: []int{9496}},
	"Pockau":                            PLZ{Name: "Pockau", Code: []int{9509}},
	"Pohl":                              PLZ{Name: "Pohl", Code: []int{8543}},
	"Pohla":                             PLZ{Name: "Pohla", Code: []int{8352}},
	"Porschdorf":                        PLZ{Name: "Porschdorf", Code: []int{1814}},
	"Pretzschendorf":                    PLZ{Name: "Pretzschendorf", Code: []int{1774}},
	"Priestewitz":                       PLZ{Name: "Priestewitz", Code: []int{1561}},
	"Pulsnitz":                          PLZ{Name: "Pulsnitz", Code: []int{1896}},
	"Puschwitz":                         PLZ{Name: "Puschwitz", Code: []int{2699}},
	"Quitzdorf Am See":                  PLZ{Name: "Quitzdorf Am See", Code: []int{2906}},
	"Rabenau":                           PLZ{Name: "Rabenau", Code: []int{1734}},
	"Rackelwitz":                        PLZ{Name: "Rackelwitz", Code: []int{1920}},
	"Rackwitz":                          PLZ{Name: "Rackwitz", Code: []int{4519}},
	"Radeberg":                          PLZ{Name: "Radeberg", Code: []int{1454}},
	"Radebeul":                          PLZ{Name: "Radebeul", Code: []int{1445}},
	"Radeburg":                          PLZ{Name: "Radeburg", Code: []int{1471}},
	"Radibor":                           PLZ{Name: "Radibor", Code: []int{2627}},
	"Ralbitz-Rosenthal":                 PLZ{Name: "Ralbitz-Rosenthal", Code: []int{1920}},
	"Rammenau":                          PLZ{Name: "Rammenau", Code: []int{1877}},
	"Raschau":                           PLZ{Name: "Raschau", Code: []int{8352}},
	"Rathen":                            PLZ{Name: "Rathen", Code: []int{1824}},
	"Rathmannsdorf":                     PLZ{Name: "Rathmannsdorf", Code: []int{1814}},
	"Rechenberg-Bienenmuhle":            PLZ{Name: "Rechenberg-Bienenmuhle", Code: []int{9623}},
	"Regis-Breitingen":                  PLZ{Name: "Regis-Breitingen", Code: []int{4565}},
	"Reichenbach/Oberlausitz":           PLZ{Name: "Reichenbach/Oberlausitz", Code: []int{2894}},
	"Reichenbach/Vogtland":              PLZ{Name: "Reichenbach/Vogtland", Code: []int{8468}},
	"Reinhardtsdorf-Schona":             PLZ{Name: "Reinhardtsdorf-Schona", Code: []int{1814}},
	"Reinhardtsgrimma":                  PLZ{Name: "Reinhardtsgrimma", Code: []int{1768}},
	"Reinsberg":                         PLZ{Name: "Reinsberg", Code: []int{9629}},
	"Reinsdorf":                         PLZ{Name: "Reinsdorf", Code: []int{8141}},
	"Remse":                             PLZ{Name: "Remse", Code: []int{8373}},
	"Reuth":                             PLZ{Name: "Reuth", Code: []int{8538}},
	"Riesa":                             PLZ{Name: "Riesa", Code: []int{1587, 1589, 1591}},
	"Rietschen":                         PLZ{Name: "Rietschen", Code: []int{2956}},
	"Rittersgrun":                       PLZ{Name: "Rittersgrun", Code: []int{8355}},
	"Rochlitz":                          PLZ{Name: "Rochlitz", Code: []int{9306}},
	"Roderaue":                          PLZ{Name: "Roderaue", Code: []int{1619}},
	"Rodewisch":                         PLZ{Name: "Rodewisch", Code: []int{8228}},
	"Rohrsdorf":                         PLZ{Name: "Rohrsdorf", Code: []int{9247}},
	"Rosenbach":                         PLZ{Name: "Rosenbach", Code: []int{2708}},
	"Rosenthal-Bielatal":                PLZ{Name: "Rosenthal-Bielatal", Code: []int{1824}},
	"Rossau":                            PLZ{Name: "Rossau", Code: []int{9661}},
	"Roswein":                           PLZ{Name: "Roswein", Code: []int{4741}},
	"Rotha":                             PLZ{Name: "Rotha", Code: []int{4571}},
	"Rothenburg/Oberlausitz":            PLZ{Name: "Rothenburg/Oberlausitz", Code: []int{2929}},
	"Sankt Egidien":                     PLZ{Name: "Sankt Egidien", Code: []int{9356}},
	"Sayda":                             PLZ{Name: "Sayda", Code: []int{9619}},
	"Scharfenstein":                     PLZ{Name: "Scharfenstein", Code: []int{9435}},
	"Scheibenberg":                      PLZ{Name: "Scheibenberg", Code: []int{9481}},
	"Schildau":                          PLZ{Name: "Schildau", Code: []int{4889}},
	"Schirgiswalde":                     PLZ{Name: "Schirgiswalde", Code: []int{2681}},
	"Schkeuditz":                        PLZ{Name: "Schkeuditz", Code: []int{4435}},
	"Schlegel":                          PLZ{Name: "Schlegel", Code: []int{2788}},
	"Schleife":                          PLZ{Name: "Schleife", Code: []int{2959}},
	"Schlema":                           PLZ{Name: "Schlema", Code: []int{8301}},
	"Schlettau":                         PLZ{Name: "Schlettau", Code: []int{9487}},
	"Schmiedeberg":                      PLZ{Name: "Schmiedeberg", Code: []int{1762}},
	"Schmolln-Putzkau":                  PLZ{Name: "Schmolln-Putzkau", Code: []int{1877}},
	"Schneeberg":                        PLZ{Name: "Schneeberg", Code: []int{8289}},
	"Schonau-Berzdorf Auf Dem Eigen":    PLZ{Name: "Schonau-Berzdorf Auf Dem Eigen", Code: []int{2899}},
	"Schonbach":                         PLZ{Name: "Schonbach", Code: []int{2708}},
	"Schonberg":                         PLZ{Name: "Schonberg", Code: []int{8393}},
	"Schoneck/Vogtland":                 PLZ{Name: "Schoneck/Vogtland", Code: []int{8261}},
	"Schonfeld":                         PLZ{Name: "Schonfeld", Code: []int{1561}},
	"Schonheide":                        PLZ{Name: "Schonheide", Code: []int{8304}},
	"Schonteichen":                      PLZ{Name: "Schonteichen", Code: []int{1920}},
	"Schonwolkau":                       PLZ{Name: "Schonwolkau", Code: []int{4509}},
	"Schopstal":                         PLZ{Name: "Schopstal", Code: []int{2829}},
	"Schwarzenberg/Erzgebirge":          PLZ{Name: "Schwarzenberg/Erzgebirge", Code: []int{8340}},
	"Schwepnitz":                        PLZ{Name: "Schwepnitz", Code: []int{1936}},
	"Sebnitz":                           PLZ{Name: "Sebnitz", Code: []int{1855}},
	"Seelitz":                           PLZ{Name: "Seelitz", Code: []int{9306}},
	"Sehmatal":                          PLZ{Name: "Sehmatal", Code: []int{9465}},
	"Seiffen/Erzgebirge":                PLZ{Name: "Seiffen/Erzgebirge", Code: []int{9548}},
	"Seifhennersdorf":                   PLZ{Name: "Seifhennersdorf", Code: []int{2782}},
	"Sellerhausen-Stunz":                PLZ{Name: "Sellerhausen-Stunz", Code: []int{4328}},
	"Siebenlehn":                        PLZ{Name: "Siebenlehn", Code: []int{9634}},
	"Sohland Am Rotstein":               PLZ{Name: "Sohland Am Rotstein", Code: []int{2894}},
	"Sohland An Der Spree":              PLZ{Name: "Sohland An Der Spree", Code: []int{2689}},
	"Sornzig-Ablas":                     PLZ{Name: "Sornzig-Ablas", Code: []int{4769}},
	"Sosa":                              PLZ{Name: "Sosa", Code: []int{8326}},
	"Spreetal":                          PLZ{Name: "Spreetal", Code: []int{2979}},
	"Stadt Wehlen":                      PLZ{Name: "Stadt Wehlen", Code: []int{1829}},
	"Stauchitz":                         PLZ{Name: "Stauchitz", Code: []int{1594}},
	"Steina":                            PLZ{Name: "Steina", Code: []int{1920}},
	"Steinberg":                         PLZ{Name: "Steinberg", Code: []int{8237}},
	"Steinigtwolmsdorf":                 PLZ{Name: "Steinigtwolmsdorf", Code: []int{1904}},
	"Steinpleis":                        PLZ{Name: "Steinpleis", Code: []int{8432}},
	"Stollberg/Erzgebirge":              PLZ{Name: "Stollberg/Erzgebirge", Code: []int{9366}},
	"Stolpen":                           PLZ{Name: "Stolpen", Code: []int{1833}},
	"Strahwalde":                        PLZ{Name: "Strahwalde", Code: []int{2747}},
	"Strasgrabchen":                     PLZ{Name: "Strasgrabchen", Code: []int{1936}},
	"Strehla":                           PLZ{Name: "Strehla", Code: []int{1616}},
	"Striegistal":                       PLZ{Name: "Striegistal", Code: []int{9661}},
	"Struppen":                          PLZ{Name: "Struppen", Code: []int{1796}},
	"Stutzengrun":                       PLZ{Name: "Stutzengrun", Code: []int{8328}},
	"Syrau":                             PLZ{Name: "Syrau", Code: []int{8548}},
	"Tannenberg":                        PLZ{Name: "Tannenberg", Code: []int{9468}},
	"Tannenbergsthal/Vogtland":          PLZ{Name: "Tannenbergsthal/Vogtland", Code: []int{8262}},
	"Taubenheim":                        PLZ{Name: "Taubenheim", Code: []int{1665}},
	"Taucha":                            PLZ{Name: "Taucha", Code: []int{4425}},
	"Taura":                             PLZ{Name: "Taura", Code: []int{9249}},
	"Tauscha":                           PLZ{Name: "Tauscha", Code: []int{1561}},
	"Thalheim / Erzgebirge":             PLZ{Name: "Thalheim / Erzgebirge", Code: []int{9380}},
	"Thallwitz":                         PLZ{Name: "Thallwitz", Code: []int{4808}},
	"Tharandt":                          PLZ{Name: "Tharandt", Code: []int{1737}},
	"Theuma":                            PLZ{Name: "Theuma", Code: []int{8541}},
	"Thiendorf":                         PLZ{Name: "Thiendorf", Code: []int{1561}},
	"Thum":                              PLZ{Name: "Thum", Code: []int{9419}},
	"Thummlitzwalde":                    PLZ{Name: "Thummlitzwalde", Code: []int{4668}},
	"Tiefenbach":                        PLZ{Name: "Tiefenbach", Code: []int{9661}},
	"Tirpersdorf":                       PLZ{Name: "Tirpersdorf", Code: []int{8606}},
	"Torgau":                            PLZ{Name: "Torgau", Code: []int{4860}},
	"Trebendorf":                        PLZ{Name: "Trebendorf", Code: []int{2959}},
	"Trebsen/Mulde":                     PLZ{Name: "Trebsen/Mulde", Code: []int{4687}},
	"Treuen":                            PLZ{Name: "Treuen", Code: []int{8233}},
	"Triebel/Vogtland":                  PLZ{Name: "Triebel/Vogtland", Code: []int{8606}},
	"Triebischtal":                      PLZ{Name: "Triebischtal", Code: []int{1665}},
	"Trossin":                           PLZ{Name: "Trossin", Code: []int{4880}},
	"Uhyst":                             PLZ{Name: "Uhyst", Code: []int{2999}},
	"Venusberg":                         PLZ{Name: "Venusberg", Code: []int{9430}},
	"Vierkirchen":                       PLZ{Name: "Vierkirchen", Code: []int{2894}},
	"Vogtlandisches Oberland":           PLZ{Name: "Vogtlandisches Oberland", Code: []int{7952, 7985}},
	"Wachau":                            PLZ{Name: "Wachau", Code: []int{1454}},
	"Waldenburg":                        PLZ{Name: "Waldenburg", Code: []int{8396}},
	"Waldheim":                          PLZ{Name: "Waldheim", Code: []int{4736}},
	"Waldhufen":                         PLZ{Name: "Waldhufen", Code: []int{2906}},
	"Waldkirchen/Erzgebirge":            PLZ{Name: "Waldkirchen/Erzgebirge", Code: []int{9437}},
	"Waltersdorf":                       PLZ{Name: "Waltersdorf", Code: []int{2799}},
	"Wechselburg":                       PLZ{Name: "Wechselburg", Code: []int{9306}},
	"Weinbohla":                         PLZ{Name: "Weinbohla", Code: []int{1689}},
	"Weischlitz":                        PLZ{Name: "Weischlitz", Code: []int{8538}},
	"Weisenberg":                        PLZ{Name: "Weisenberg", Code: []int{2627}},
	"Weisenborn/Erzgebirge":             PLZ{Name: "Weisenborn/Erzgebirge", Code: []int{9600}},
	"Weisig Am Raschutz":                PLZ{Name: "Weisig Am Raschutz", Code: []int{1561}},
	"Weiskeisel":                        PLZ{Name: "Weiskeisel", Code: []int{2957}},
	"Weiswasser":                        PLZ{Name: "Weiswasser", Code: []int{2943}},
	"Weixdorf":                          PLZ{Name: "Weixdorf", Code: []int{1108}},
	"Werda":                             PLZ{Name: "Werda", Code: []int{8223}},
	"Werdau":                            PLZ{Name: "Werdau", Code: []int{8412}},
	"Wermsdorf":                         PLZ{Name: "Wermsdorf", Code: []int{4779}},
	"Wiedemar":                          PLZ{Name: "Wiedemar", Code: []int{4509}},
	"Wiednitz":                          PLZ{Name: "Wiednitz", Code: []int{2994}},
	"Wiesa":                             PLZ{Name: "Wiesa", Code: []int{9488}},
	"Wildenfels":                        PLZ{Name: "Wildenfels", Code: []int{8134}},
	"Wildenfels Hartensdorf":            PLZ{Name: "Wildenfels Hartensdorf", Code: []int{8134}},
	"Wildenfels Schonau":                PLZ{Name: "Wildenfels Schonau", Code: []int{8134}},
	"Wildenfels Wiesen":                 PLZ{Name: "Wildenfels Wiesen", Code: []int{8134}},
	"Wildenfels Wiesenburg":             PLZ{Name: "Wildenfels Wiesenburg", Code: []int{8134}},
	"Wildenfels Wildenfels":             PLZ{Name: "Wildenfels Wildenfels", Code: []int{8134}},
	"Wildenhain":                        PLZ{Name: "Wildenhain", Code: []int{1561}},
	"Wilkau-Haslau":                     PLZ{Name: "Wilkau-Haslau", Code: []int{8112}},
	"Wilschdorf":                        PLZ{Name: "Wilschdorf", Code: []int{1109}},
	"Wilsdruff":                         PLZ{Name: "Wilsdruff", Code: []int{1723}},
	"Wilthen":                           PLZ{Name: "Wilthen", Code: []int{2681}},
	"Wittgensdorf":                      PLZ{Name: "Wittgensdorf", Code: []int{9228}},
	"Wittichenau":                       PLZ{Name: "Wittichenau", Code: []int{2997}},
	"Wolkenstein":                       PLZ{Name: "Wolkenstein", Code: []int{9429}},
	"Wulknitz":                          PLZ{Name: "Wulknitz", Code: []int{1609}},
	"Wurzen":                            PLZ{Name: "Wurzen", Code: []int{4808}},
	"Wyhratal":                          PLZ{Name: "Wyhratal", Code: []int{4552}},
	"Zabeltitz":                         PLZ{Name: "Zabeltitz", Code: []int{1561}},
	"Zeithain":                          PLZ{Name: "Zeithain", Code: []int{1619}},
	"Zettlitz":                          PLZ{Name: "Zettlitz", Code: []int{9306}},
	"Ziegra-Knobelsdorf":                PLZ{Name: "Ziegra-Knobelsdorf", Code: []int{4720}},
	"Zinna":                             PLZ{Name: "Zinna", Code: []int{4860}},
	"Zittau":                            PLZ{Name: "Zittau", Code: []int{2763}},
	"Zoblitz":                           PLZ{Name: "Zoblitz", Code: []int{9517}},
	"Zschadras":                         PLZ{Name: "Zschadras", Code: []int{4680}},
	"Zschaitz-Ottewig":                  PLZ{Name: "Zschaitz-Ottewig", Code: []int{4720}},
	"Zschepplin":                        PLZ{Name: "Zschepplin", Code: []int{4838}},
	"Zschopau":                          PLZ{Name: "Zschopau", Code: []int{9405}},
	"Zschorlau":                         PLZ{Name: "Zschorlau", Code: []int{8321}},
	"Zschortau":                         PLZ{Name: "Zschortau", Code: []int{4509}},
	"Zwenkau":                           PLZ{Name: "Zwenkau", Code: []int{4442}},
	"Zwickau":                           PLZ{Name: "Zwickau", Code: []int{8056, 8058, 8060, 8062, 8064, 8066}},
	"Zwochau":                           PLZ{Name: "Zwochau", Code: []int{4509}},
	"Zwonitz":                           PLZ{Name: "Zwonitz", Code: []int{8297}},
	"Zwota":                             PLZ{Name: "Zwota", Code: []int{8267}},
}
var sachsen_slice = []PLZ{
	PLZ{Name: "Adorf", Code: []int{8626}},
	PLZ{Name: "Altenberg", Code: []int{1773}},
	PLZ{Name: "Altmittweida", Code: []int{9648}},
	PLZ{Name: "Amtsberg", Code: []int{9439}},
	PLZ{Name: "Annaberg-Buchholz", Code: []int{9456}},
	PLZ{Name: "Arnsdorf", Code: []int{1477}},
	PLZ{Name: "Arzberg", Code: []int{4886}},
	PLZ{Name: "Aue", Code: []int{8280}},
	PLZ{Name: "Auerbach", Code: []int{9392}},
	PLZ{Name: "Auerbach/Vogtland", Code: []int{8209}},
	PLZ{Name: "Augustusburg", Code: []int{9573}},
	PLZ{Name: "Bad Brambach", Code: []int{8648}},
	PLZ{Name: "Bad Duben", Code: []int{4849}},
	PLZ{Name: "Bad Elster", Code: []int{8645}},
	PLZ{Name: "Bad Gottleuba-Berggieshubel", Code: []int{1816}},
	PLZ{Name: "Bad Lausick", Code: []int{4651}},
	PLZ{Name: "Bad Muskau", Code: []int{2953}},
	PLZ{Name: "Bad Schandau", Code: []int{1814}},
	PLZ{Name: "Bahretal", Code: []int{1819}},
	PLZ{Name: "Bannewitz", Code: []int{1728}},
	PLZ{Name: "Barenstein", Code: []int{1768, 9471}},
	PLZ{Name: "Bautzen", Code: []int{2625}},
	PLZ{Name: "Beierfeld", Code: []int{8340}},
	PLZ{Name: "Beiersdorf", Code: []int{2736}},
	PLZ{Name: "Beilrode", Code: []int{4886}},
	PLZ{Name: "Belgern", Code: []int{4874}},
	PLZ{Name: "Belgershain", Code: []int{4683}},
	PLZ{Name: "Bennewitz", Code: []int{4828}},
	PLZ{Name: "Bergen", Code: []int{8239}},
	PLZ{Name: "Bernsbach", Code: []int{8315}},
	PLZ{Name: "Bernsdorf", Code: []int{2994, 9337}},
	PLZ{Name: "Bernstadt Auf Dem Eigen", Code: []int{2748}},
	PLZ{Name: "Berthelsdorf", Code: []int{2747}},
	PLZ{Name: "Bertsdorf-Hornitz", Code: []int{2763}},
	PLZ{Name: "Beucha", Code: []int{4824}},
	PLZ{Name: "Bischofswerda", Code: []int{1877}},
	PLZ{Name: "Bobritzsch", Code: []int{9627}},
	PLZ{Name: "Bockau", Code: []int{8324}},
	PLZ{Name: "Bockelwitz", Code: []int{4703}},
	PLZ{Name: "Bohlen", Code: []int{4564}},
	PLZ{Name: "Borna", Code: []int{4552}},
	PLZ{Name: "Bornichen/Erzgebirge", Code: []int{9437}},
	PLZ{Name: "Borsdorf", Code: []int{4451}},
	PLZ{Name: "Borstendorf", Code: []int{9579}},
	PLZ{Name: "Bosenbrunn", Code: []int{8606}},
	PLZ{Name: "Boxberg/Oberlausitz", Code: []int{2943}},
	PLZ{Name: "Brand-Erbisdorf", Code: []int{9618}},
	PLZ{Name: "Brandis", Code: []int{4821}},
	PLZ{Name: "Breitenbrunn/Erzgebirge", Code: []int{8359}},
	PLZ{Name: "Breitenfeld", Code: []int{4158}},
	PLZ{Name: "Bretnig-Hauswalde", Code: []int{1900}},
	PLZ{Name: "Burghausen", Code: []int{4178}},
	PLZ{Name: "Burgstadt", Code: []int{9217}},
	PLZ{Name: "Burgstein", Code: []int{8538}},
	PLZ{Name: "Burkau", Code: []int{1906}},
	PLZ{Name: "Burkhardtsdorf", Code: []int{9235}},
	PLZ{Name: "Callenberg", Code: []int{9337}},
	PLZ{Name: "Carlsfeld, Erzgebirge", Code: []int{8325}},
	PLZ{Name: "Cavertitz", Code: []int{4758}},
	PLZ{Name: "Chemnitz", Code: []int{9111, 9112, 9113, 9114, 9116, 9117, 9119, 9120, 9122, 9123, 9125, 9126, 9127, 9130, 9131}},
	PLZ{Name: "Chemnitz, Sachsen", Code: []int{9028, 9030, 9128}},
	PLZ{Name: "Clausnitz", Code: []int{9236}},
	PLZ{Name: "Colditz", Code: []int{4680}},
	PLZ{Name: "Coswig", Code: []int{1640}},
	PLZ{Name: "Crimmitschau", Code: []int{8451}},
	PLZ{Name: "Crinitzberg", Code: []int{8147}},
	PLZ{Name: "Crostau", Code: []int{2681}},
	PLZ{Name: "Crostwitz", Code: []int{1920}},
	PLZ{Name: "Crottendorf", Code: []int{9474}},
	PLZ{Name: "Cunewalde", Code: []int{2733}},
	PLZ{Name: "Dahlen", Code: []int{4774}},
	PLZ{Name: "Delitzsch", Code: []int{4509}},
	PLZ{Name: "Demitz-Thumitz", Code: []int{1877}},
	PLZ{Name: "Dennheritz", Code: []int{8393}},
	PLZ{Name: "Deutschneudorf", Code: []int{9548}},
	PLZ{Name: "Deutzen", Code: []int{4574}},
	PLZ{Name: "Diera-Zehren", Code: []int{1665}},
	PLZ{Name: "Diesbar-Seuslitz", Code: []int{1612}},
	PLZ{Name: "Dippoldiswalde", Code: []int{1744}},
	PLZ{Name: "Dobeln", Code: []int{4720}},
	PLZ{Name: "Dobernitz", Code: []int{4509}},
	PLZ{Name: "Doberschau-Gausig", Code: []int{1877, 2633, 2692}},
	PLZ{Name: "Doberschutz", Code: []int{4838}},
	PLZ{Name: "Dohma", Code: []int{1796}},
	PLZ{Name: "Dohna", Code: []int{1809}},
	PLZ{Name: "Dommitzsch", Code: []int{4880}},
	PLZ{Name: "Dorfchemnitz Bei Sayda", Code: []int{9619}},
	PLZ{Name: "Dorfhain", Code: []int{1738}},
	PLZ{Name: "Drebach", Code: []int{9430}},
	PLZ{Name: "Dreiheide", Code: []int{4860}},
	PLZ{Name: "Dresden", Code: []int{1067, 1069, 1097, 1099, 1108, 1109, 1127, 1129, 1139, 1156, 1157, 1159, 1169, 1187, 1189, 1217, 1219, 1237, 1239, 1257, 1259, 1277, 1279, 1307, 1309, 1324, 1326, 1328, 1465}},
	PLZ{Name: "Dresden Altfranken", Code: []int{1156}},
	PLZ{Name: "Dresden Blasewitz", Code: []int{1309}},
	PLZ{Name: "Dresden Friedrichstadt", Code: []int{1067}},
	PLZ{Name: "Dresden Gompitz", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Gompitz", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Ockerwitz", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Pennrich", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Roitzsch", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Steinbach", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Unkersdorf", Code: []int{1156}},
	PLZ{Name: "Dresden Gompitz, Zollmen", Code: []int{1156}},
	PLZ{Name: "Dresden Innere Altstadt", Code: []int{1067}},
	PLZ{Name: "Dresden Langebruck", Code: []int{1465}},
	PLZ{Name: "Dresden Striesen", Code: []int{1277}},
	PLZ{Name: "Dresden Tolkewitz", Code: []int{1277, 1279}},
	PLZ{Name: "Durrhennersdorf", Code: []int{2708}},
	PLZ{Name: "Durrrohrsdorf-Dittersbach", Code: []int{1833}},
	PLZ{Name: "Ebersbach", Code: []int{1561, 4720}},
	PLZ{Name: "Ebersbach/Sachsen", Code: []int{2730}},
	PLZ{Name: "Ehrenfriedersdorf", Code: []int{9427}},
	PLZ{Name: "Eibau", Code: []int{2739}},
	PLZ{Name: "Eibenstock", Code: []int{8309}},
	PLZ{Name: "Eichigt", Code: []int{8626}},
	PLZ{Name: "Eilenburg", Code: []int{4838}},
	PLZ{Name: "Einsiedel Bei Chemnitz", Code: []int{9227}},
	PLZ{Name: "Ellefeld", Code: []int{8236}},
	PLZ{Name: "Elsnig", Code: []int{4880}},
	PLZ{Name: "Elsterberg", Code: []int{7985}},
	PLZ{Name: "Elsterheide", Code: []int{2979, 2991}},
	PLZ{Name: "Elstertrebnitz", Code: []int{4523}},
	PLZ{Name: "Elstra", Code: []int{1920}},
	PLZ{Name: "Elterlein", Code: []int{9481}},
	PLZ{Name: "Eppendorf", Code: []int{9575}},
	PLZ{Name: "Erlabrunn", Code: []int{8349}},
	PLZ{Name: "Erlau", Code: []int{9306}},
	PLZ{Name: "Erlbach", Code: []int{8265}},
	PLZ{Name: "Erlbach-Kirchberg", Code: []int{9385}},
	PLZ{Name: "Espenhain", Code: []int{4579}},
	PLZ{Name: "Eulatal", Code: []int{4651}},
	PLZ{Name: "Eulowitz", Code: []int{2692}},
	PLZ{Name: "Falkenau", Code: []int{9569}},
	PLZ{Name: "Falkenhain", Code: []int{4808}},
	PLZ{Name: "Falkenstein/Vogtland", Code: []int{8223}},
	PLZ{Name: "Floha", Code: []int{9557}},
	PLZ{Name: "Frankenberg/Sachsen", Code: []int{9669}},
	PLZ{Name: "Frankenstein", Code: []int{9569}},
	PLZ{Name: "Frankenthal", Code: []int{1909}},
	PLZ{Name: "Frauenstein", Code: []int{9623}},
	PLZ{Name: "Fraureuth", Code: []int{8427}},
	PLZ{Name: "Freiberg", Code: []int{9599}},
	PLZ{Name: "Freital", Code: []int{1705}},
	PLZ{Name: "Friedersdorf", Code: []int{2742}},
	PLZ{Name: "Frohburg", Code: []int{4654}},
	PLZ{Name: "Gablenz", Code: []int{2953}},
	PLZ{Name: "Gahlenz", Code: []int{9569}},
	PLZ{Name: "Geising", Code: []int{1778}},
	PLZ{Name: "Geithain", Code: []int{4643}},
	PLZ{Name: "Gelenau/Erzgebirge", Code: []int{9423}},
	PLZ{Name: "Geringswalde", Code: []int{9326}},
	PLZ{Name: "Gersdorf", Code: []int{4703, 9355}},
	PLZ{Name: "Geyer", Code: []int{9468}},
	PLZ{Name: "Glashutte", Code: []int{1768}},
	PLZ{Name: "Glaubitz", Code: []int{1612}},
	PLZ{Name: "Glauchau", Code: []int{8371}},
	PLZ{Name: "Goda", Code: []int{2633}},
	PLZ{Name: "Gohrisch", Code: []int{1824}},
	PLZ{Name: "Gorlitz", Code: []int{2826, 2827, 2828}},
	PLZ{Name: "Gornau/Erzgebirge", Code: []int{9405}},
	PLZ{Name: "Gornsdorf", Code: []int{9390}},
	PLZ{Name: "Grimma", Code: []int{4668}},
	PLZ{Name: "Groditz", Code: []int{1609}},
	PLZ{Name: "Groitzsch", Code: []int{4539}},
	PLZ{Name: "Gros Duben", Code: []int{2959}},
	PLZ{Name: "Grosbardau", Code: []int{4668}},
	PLZ{Name: "Grosbothen", Code: []int{4668}},
	PLZ{Name: "Grosdubrau", Code: []int{2694}},
	PLZ{Name: "Grosenhain", Code: []int{1558}},
	PLZ{Name: "Grosharthau", Code: []int{1909}},
	PLZ{Name: "Groshartmannsdorf", Code: []int{9618}},
	PLZ{Name: "Groshennersdorf", Code: []int{2747}},
	PLZ{Name: "Groslehna", Code: []int{4420}},
	PLZ{Name: "Grosnaundorf", Code: []int{1936}},
	PLZ{Name: "Grosolbersdorf", Code: []int{9432}},
	PLZ{Name: "Grosposna", Code: []int{4463}},
	PLZ{Name: "Grospostwitz/Oberlausitz", Code: []int{2692}},
	PLZ{Name: "Grosrohrsdorf", Code: []int{1900}},
	PLZ{Name: "Grosruckerswalde", Code: []int{9518}},
	PLZ{Name: "Grosschirma", Code: []int{9603}},
	PLZ{Name: "Grosschonau", Code: []int{2779}},
	PLZ{Name: "Grosschweidnitz", Code: []int{2708}},
	PLZ{Name: "Grostreben-Zwethau", Code: []int{4886}},
	PLZ{Name: "Grosweitzschen", Code: []int{4720}},
	PLZ{Name: "Grunbach", Code: []int{8223}},
	PLZ{Name: "Grunhain", Code: []int{8344}},
	PLZ{Name: "Grunhainichen", Code: []int{9579}},
	PLZ{Name: "Guttau", Code: []int{2694}},
	PLZ{Name: "Hahnichen", Code: []int{2923}},
	PLZ{Name: "Hainewalde", Code: []int{2779}},
	PLZ{Name: "Hainichen", Code: []int{9661}},
	PLZ{Name: "Halsbrucke", Code: []int{9633}},
	PLZ{Name: "Hammerbrucke", Code: []int{8269}},
	PLZ{Name: "Hartenstein", Code: []int{8118}},
	PLZ{Name: "Hartenstein Hartenstein", Code: []int{8118}},
	PLZ{Name: "Hartenstein Thierfeld", Code: []int{8118}},
	PLZ{Name: "Hartenstein Zschocken", Code: []int{8118}},
	PLZ{Name: "Hartha", Code: []int{4746}},
	PLZ{Name: "Hartmannsdorf", Code: []int{9232}},
	PLZ{Name: "Hartmannsdorf Bei Kirchberg", Code: []int{8107}},
	PLZ{Name: "Hartmannsdorf-Reichenau", Code: []int{1762}},
	PLZ{Name: "Haselbachtal", Code: []int{1920, 1936}},
	PLZ{Name: "Heidenau", Code: []int{1809}},
	PLZ{Name: "Heidersdorf", Code: []int{9526}},
	PLZ{Name: "Heinsdorfergrund", Code: []int{8468}},
	PLZ{Name: "Hellerau", Code: []int{1109}},
	PLZ{Name: "Hermsdorf/Erzgebirge", Code: []int{1776}},
	PLZ{Name: "Herrnhut", Code: []int{2747}},
	PLZ{Name: "Heuersdorf", Code: []int{4574}},
	PLZ{Name: "Heynitz", Code: []int{1683}},
	PLZ{Name: "Hilbersdorf", Code: []int{9627}},
	PLZ{Name: "Hirschfeld", Code: []int{8107, 8144}},
	PLZ{Name: "Hirschfelde", Code: []int{2788}},
	PLZ{Name: "Hirschfelde Dittelsdorf", Code: []int{2788}},
	PLZ{Name: "Hirschstein", Code: []int{1594}},
	PLZ{Name: "Hochkirch", Code: []int{2627}},
	PLZ{Name: "Hockendorf", Code: []int{1774}},
	PLZ{Name: "Hohburg", Code: []int{4808}},
	PLZ{Name: "Hohendubrau", Code: []int{2906}},
	PLZ{Name: "Hohenstein-Ernstthal", Code: []int{9337}},
	PLZ{Name: "Hohndorf", Code: []int{9394}},
	PLZ{Name: "Hohnstein", Code: []int{1848}},
	PLZ{Name: "Hohwald", Code: []int{1844}},
	PLZ{Name: "Horka", Code: []int{2923}},
	PLZ{Name: "Hormersdorf", Code: []int{9395}},
	PLZ{Name: "Hoyerswerda", Code: []int{2977}},
	PLZ{Name: "Hundshubel", Code: []int{8318}},
	PLZ{Name: "Jahnsdorf/Erzgebirge", Code: []int{9387}},
	PLZ{Name: "Jesewitz", Code: []int{4838}},
	PLZ{Name: "Johanngeorgenstadt", Code: []int{8349}},
	PLZ{Name: "Johstadt", Code: []int{9477}},
	PLZ{Name: "Jonsdorf", Code: []int{2796}},
	PLZ{Name: "Josnitz", Code: []int{8547}},
	PLZ{Name: "Kabschutztal", Code: []int{1665}},
	PLZ{Name: "Kamenz", Code: []int{1917}},
	PLZ{Name: "Kandler", Code: []int{9212}},
	PLZ{Name: "Ketzerbachtal", Code: []int{1623}},
	PLZ{Name: "Kirchberg", Code: []int{8107}},
	PLZ{Name: "Kirnitzschtal", Code: []int{1855}},
	PLZ{Name: "Kirschau", Code: []int{2681}},
	PLZ{Name: "Kittlitz", Code: []int{2708}},
	PLZ{Name: "Kitzen", Code: []int{4460}},
	PLZ{Name: "Kitzscher", Code: []int{4567}},
	PLZ{Name: "Klingenthal/Sachsen", Code: []int{8248}},
	PLZ{Name: "Klipphausen", Code: []int{1665}},
	PLZ{Name: "Klitten", Code: []int{2906}},
	PLZ{Name: "Klotzsche", Code: []int{1109}},
	PLZ{Name: "Knappensee", Code: []int{2999}},
	PLZ{Name: "Kodersdorf", Code: []int{2923}},
	PLZ{Name: "Kohren-Sahlis", Code: []int{4655}},
	PLZ{Name: "Konigsbruck", Code: []int{1936}},
	PLZ{Name: "Konigsfeld", Code: []int{9306}},
	PLZ{Name: "Konigshain", Code: []int{2829}},
	PLZ{Name: "Konigshain-Wiederau", Code: []int{9306}},
	PLZ{Name: "Konigstein/Sachsische Schweiz", Code: []int{1824}},
	PLZ{Name: "Konigswalde", Code: []int{9471}},
	PLZ{Name: "Konigswartha", Code: []int{2699}},
	PLZ{Name: "Kossa", Code: []int{4849}},
	PLZ{Name: "Krauschwitz", Code: []int{2957}},
	PLZ{Name: "Kreba-Neudorf", Code: []int{2906}},
	PLZ{Name: "Kreischa", Code: []int{1731}},
	PLZ{Name: "Kriebstein", Code: []int{9648}},
	PLZ{Name: "Krostitz", Code: []int{4509}},
	PLZ{Name: "Kubschutz", Code: []int{2627}},
	PLZ{Name: "Kuhren-Burkartshain", Code: []int{4808}},
	PLZ{Name: "Lampertswalde", Code: []int{1561}},
	PLZ{Name: "Langenbernsdorf", Code: []int{8428}},
	PLZ{Name: "Langenhessen", Code: []int{8439}},
	PLZ{Name: "Langenweisbach", Code: []int{8134}},
	PLZ{Name: "Langenweisbach Grunau", Code: []int{8134}},
	PLZ{Name: "Langenweisbach Langenbach", Code: []int{8134}},
	PLZ{Name: "Langenweisbach Weisbach", Code: []int{8134}},
	PLZ{Name: "Lausig", Code: []int{4838}},
	PLZ{Name: "Lausnitz", Code: []int{1936}},
	PLZ{Name: "Lauta", Code: []int{2991}},
	PLZ{Name: "Lauter/Sachsen", Code: []int{8312}},
	PLZ{Name: "Lawalde", Code: []int{2708}},
	PLZ{Name: "Leippe-Torno", Code: []int{2991}},
	PLZ{Name: "Leipzig", Code: []int{4103, 4105, 4107, 4109, 4129, 4155, 4157, 4159, 4177, 4179, 4205, 4207, 4209, 4229, 4249, 4275, 4277, 4279, 4288, 4289, 4299, 4315, 4316, 4317, 4318, 4319, 4329, 4347, 4349, 4356, 4357}},
	PLZ{Name: "Leisnig", Code: []int{4703}},
	PLZ{Name: "Lengefeld", Code: []int{9514}},
	PLZ{Name: "Lengenfeld", Code: []int{8485}},
	PLZ{Name: "Leuben-Schleinitz", Code: []int{1623}},
	PLZ{Name: "Leubnitz", Code: []int{8412}},
	PLZ{Name: "Leubsdorf", Code: []int{9573}},
	PLZ{Name: "Leutersdorf", Code: []int{2794}},
	PLZ{Name: "Lichtenau", Code: []int{9244}},
	PLZ{Name: "Lichtenberg", Code: []int{1896}},
	PLZ{Name: "Lichtenberg/Erzgebirge", Code: []int{9638}},
	PLZ{Name: "Lichtenstein/Sachsen", Code: []int{9350}},
	PLZ{Name: "Lichtentanne", Code: []int{8115}},
	PLZ{Name: "Liebschutzberg", Code: []int{4758}},
	PLZ{Name: "Liebstadt", Code: []int{1825}},
	PLZ{Name: "Limbach", Code: []int{8491}},
	PLZ{Name: "Limbach-Oberfrohna", Code: []int{9212}},
	PLZ{Name: "Lobau", Code: []int{2708}},
	PLZ{Name: "Lobnitz", Code: []int{4509}},
	PLZ{Name: "Lobstadt", Code: []int{4552}},
	PLZ{Name: "Lohmen", Code: []int{1847}},
	PLZ{Name: "Lohsa", Code: []int{2999}},
	PLZ{Name: "Lommatzsch", Code: []int{1623}},
	PLZ{Name: "Losnitz", Code: []int{8294}},
	PLZ{Name: "Lugau/Erzgebirge", Code: []int{9385}},
	PLZ{Name: "Lunzenau", Code: []int{9328}},
	PLZ{Name: "Machern", Code: []int{4827}},
	PLZ{Name: "Malschwitz", Code: []int{2694}},
	PLZ{Name: "Marienberg", Code: []int{9496}},
	PLZ{Name: "Markersbach", Code: []int{8352}},
	PLZ{Name: "Markersdorf", Code: []int{2829}},
	PLZ{Name: "Markkleeberg", Code: []int{4416}},
	PLZ{Name: "Markneukirchen", Code: []int{8258}},
	PLZ{Name: "Markranstadt", Code: []int{4420}},
	PLZ{Name: "Marsdorf", Code: []int{1108}},
	PLZ{Name: "Meerane", Code: []int{8393}},
	PLZ{Name: "Mehltheuer", Code: []int{8539}},
	PLZ{Name: "Meisen", Code: []int{1662}},
	PLZ{Name: "Mildenau", Code: []int{9456}},
	PLZ{Name: "Mittelbach Bei Chemnitz", Code: []int{9224}},
	PLZ{Name: "Mittelherwigsdorf", Code: []int{2763}},
	PLZ{Name: "Mittweida", Code: []int{9648}},
	PLZ{Name: "Mochau", Code: []int{4720}},
	PLZ{Name: "Mockrehna", Code: []int{4838, 4862}},
	PLZ{Name: "Morgenrothe-Rautenkranz", Code: []int{8262}},
	PLZ{Name: "Moritzburg", Code: []int{1468}},
	PLZ{Name: "Mucka", Code: []int{2906}},
	PLZ{Name: "Mugeln", Code: []int{4769}},
	PLZ{Name: "Muglitztal", Code: []int{1809}},
	PLZ{Name: "Muhlau", Code: []int{9241}},
	PLZ{Name: "Muhlental", Code: []int{8606}},
	PLZ{Name: "Muhltroff", Code: []int{7919}},
	PLZ{Name: "Mulda/Sachsen", Code: []int{9619}},
	PLZ{Name: "Mulsen", Code: []int{8132}},
	PLZ{Name: "Mulsen Mulsen Sankt Jacob", Code: []int{8132}},
	PLZ{Name: "Mulsen Mulsen Sankt Micheln", Code: []int{8132}},
	PLZ{Name: "Mulsen Mulsen Sankt Niclas", Code: []int{8132}},
	PLZ{Name: "Mulsen Niedermulsen", Code: []int{8132}},
	PLZ{Name: "Mulsen Ortmannsdorf", Code: []int{8132}},
	PLZ{Name: "Mulsen Ortmannsdorf, Marienau", Code: []int{8132}},
	PLZ{Name: "Mulsen Ortmannsdorf, Neuschonburg", Code: []int{8132}},
	PLZ{Name: "Mulsen Ortmannsdorf, Ortmannsdorf", Code: []int{8132}},
	PLZ{Name: "Mulsen Stangendorf", Code: []int{8132}},
	PLZ{Name: "Mulsen Thurm", Code: []int{8132}},
	PLZ{Name: "Mulsen Wulm", Code: []int{8132}},
	PLZ{Name: "Mulsen Wulm, Bertelsdorf", Code: []int{8132}},
	PLZ{Name: "Mulsen Wulm, Wulm", Code: []int{8132}},
	PLZ{Name: "Mutzschen", Code: []int{4688}},
	PLZ{Name: "Mylau", Code: []int{8499}},
	PLZ{Name: "Narsdorf", Code: []int{4657}},
	PLZ{Name: "Naundorf", Code: []int{4769}},
	PLZ{Name: "Naunhof", Code: []int{4683}},
	PLZ{Name: "Nauwalde", Code: []int{1609}},
	PLZ{Name: "Nebelschutz", Code: []int{1920}},
	PLZ{Name: "Neiseaue", Code: []int{2829, 2923}},
	PLZ{Name: "Nerchau", Code: []int{4685}},
	PLZ{Name: "Neschwitz", Code: []int{2699}},
	PLZ{Name: "Netzschkau", Code: []int{8491}},
	PLZ{Name: "Neuensalz", Code: []int{8541}},
	PLZ{Name: "Neugersdorf", Code: []int{2727}},
	PLZ{Name: "Neuhausen/Erzgebirge", Code: []int{9544}},
	PLZ{Name: "Neukieritzsch", Code: []int{4575}},
	PLZ{Name: "Neukirch", Code: []int{1936}},
	PLZ{Name: "Neukirch/Lausitz", Code: []int{1904}},
	PLZ{Name: "Neukirchen/Erzgebirge", Code: []int{9221}},
	PLZ{Name: "Neukirchen/Pleise", Code: []int{8459}},
	PLZ{Name: "Neukyhna", Code: []int{4509}},
	PLZ{Name: "Neumark", Code: []int{8496}},
	PLZ{Name: "Neusalza-Spremberg", Code: []int{2742}},
	PLZ{Name: "Neustadt In Sachsen", Code: []int{1844}},
	PLZ{Name: "Neustadt/Vogtland", Code: []int{8223}},
	PLZ{Name: "Niederau", Code: []int{1689}},
	PLZ{Name: "Niedercunnersdorf", Code: []int{2708}},
	PLZ{Name: "Niederdorf", Code: []int{9366}},
	PLZ{Name: "Niederfrohna", Code: []int{9243}},
	PLZ{Name: "Niederschona", Code: []int{9600}},
	PLZ{Name: "Niederstriegis", Code: []int{4741}},
	PLZ{Name: "Niederwiesa", Code: []int{9577}},
	PLZ{Name: "Niederwurschnitz", Code: []int{9399}},
	PLZ{Name: "Niesky", Code: []int{2906}},
	PLZ{Name: "Nossen", Code: []int{1683}},
	PLZ{Name: "Nunchritz", Code: []int{1612}},
	PLZ{Name: "Obercunnersdorf", Code: []int{2708}},
	PLZ{Name: "Obergurig", Code: []int{2692}},
	PLZ{Name: "Oberlichtenau", Code: []int{1936}},
	PLZ{Name: "Oberlungwitz", Code: []int{9353}},
	PLZ{Name: "Oberschona", Code: []int{9600}},
	PLZ{Name: "Oberwiera", Code: []int{8396}},
	PLZ{Name: "Oberwiesenthal", Code: []int{9484}},
	PLZ{Name: "Oderwitz", Code: []int{2791}},
	PLZ{Name: "Oederan", Code: []int{9569}},
	PLZ{Name: "Oelsnitz", Code: []int{8606}},
	PLZ{Name: "Oelsnitz/Erzgebirge", Code: []int{9376}},
	PLZ{Name: "Ohorn", Code: []int{1896}},
	PLZ{Name: "Olbernhau", Code: []int{9526}},
	PLZ{Name: "Olbersdorf", Code: []int{2785}},
	PLZ{Name: "Oppach", Code: []int{2736}},
	PLZ{Name: "Oschatz", Code: []int{4758}},
	PLZ{Name: "Osling", Code: []int{1920}},
	PLZ{Name: "Ostrau", Code: []int{4749}},
	PLZ{Name: "Ostritz", Code: []int{2899}},
	PLZ{Name: "Ottendorf-Okrilla", Code: []int{1458}},
	PLZ{Name: "Otterwisch", Code: []int{4668}},
	PLZ{Name: "Oybin", Code: []int{2797}},
	PLZ{Name: "Panschwitz-Kuckau", Code: []int{1920}},
	PLZ{Name: "Parthenstein", Code: []int{4668}},
	PLZ{Name: "Pausa", Code: []int{7952}},
	PLZ{Name: "Pegau", Code: []int{4523}},
	PLZ{Name: "Penig", Code: []int{9322}},
	PLZ{Name: "Pfaffroda", Code: []int{9526}},
	PLZ{Name: "Pfluckuff", Code: []int{4860}},
	PLZ{Name: "Pirna", Code: []int{1796}},
	PLZ{Name: "Plauen", Code: []int{8523, 8525, 8527, 8529}},
	PLZ{Name: "Pleisa", Code: []int{9212}},
	PLZ{Name: "Pobershau", Code: []int{9496}},
	PLZ{Name: "Pockau", Code: []int{9509}},
	PLZ{Name: "Pohl", Code: []int{8543}},
	PLZ{Name: "Pohla", Code: []int{8352}},
	PLZ{Name: "Porschdorf", Code: []int{1814}},
	PLZ{Name: "Pretzschendorf", Code: []int{1774}},
	PLZ{Name: "Priestewitz", Code: []int{1561}},
	PLZ{Name: "Pulsnitz", Code: []int{1896}},
	PLZ{Name: "Puschwitz", Code: []int{2699}},
	PLZ{Name: "Quitzdorf Am See", Code: []int{2906}},
	PLZ{Name: "Rabenau", Code: []int{1734}},
	PLZ{Name: "Rackelwitz", Code: []int{1920}},
	PLZ{Name: "Rackwitz", Code: []int{4519}},
	PLZ{Name: "Radeberg", Code: []int{1454}},
	PLZ{Name: "Radebeul", Code: []int{1445}},
	PLZ{Name: "Radeburg", Code: []int{1471}},
	PLZ{Name: "Radibor", Code: []int{2627}},
	PLZ{Name: "Ralbitz-Rosenthal", Code: []int{1920}},
	PLZ{Name: "Rammenau", Code: []int{1877}},
	PLZ{Name: "Raschau", Code: []int{8352}},
	PLZ{Name: "Rathen", Code: []int{1824}},
	PLZ{Name: "Rathmannsdorf", Code: []int{1814}},
	PLZ{Name: "Rechenberg-Bienenmuhle", Code: []int{9623}},
	PLZ{Name: "Regis-Breitingen", Code: []int{4565}},
	PLZ{Name: "Reichenbach/Oberlausitz", Code: []int{2894}},
	PLZ{Name: "Reichenbach/Vogtland", Code: []int{8468}},
	PLZ{Name: "Reinhardtsdorf-Schona", Code: []int{1814}},
	PLZ{Name: "Reinhardtsgrimma", Code: []int{1768}},
	PLZ{Name: "Reinsberg", Code: []int{9629}},
	PLZ{Name: "Reinsdorf", Code: []int{8141}},
	PLZ{Name: "Remse", Code: []int{8373}},
	PLZ{Name: "Reuth", Code: []int{8538}},
	PLZ{Name: "Riesa", Code: []int{1587, 1589, 1591}},
	PLZ{Name: "Rietschen", Code: []int{2956}},
	PLZ{Name: "Rittersgrun", Code: []int{8355}},
	PLZ{Name: "Rochlitz", Code: []int{9306}},
	PLZ{Name: "Roderaue", Code: []int{1619}},
	PLZ{Name: "Rodewisch", Code: []int{8228}},
	PLZ{Name: "Rohrsdorf", Code: []int{9247}},
	PLZ{Name: "Rosenbach", Code: []int{2708}},
	PLZ{Name: "Rosenthal-Bielatal", Code: []int{1824}},
	PLZ{Name: "Rossau", Code: []int{9661}},
	PLZ{Name: "Roswein", Code: []int{4741}},
	PLZ{Name: "Rotha", Code: []int{4571}},
	PLZ{Name: "Rothenburg/Oberlausitz", Code: []int{2929}},
	PLZ{Name: "Sankt Egidien", Code: []int{9356}},
	PLZ{Name: "Sayda", Code: []int{9619}},
	PLZ{Name: "Scharfenstein", Code: []int{9435}},
	PLZ{Name: "Scheibenberg", Code: []int{9481}},
	PLZ{Name: "Schildau", Code: []int{4889}},
	PLZ{Name: "Schirgiswalde", Code: []int{2681}},
	PLZ{Name: "Schkeuditz", Code: []int{4435}},
	PLZ{Name: "Schlegel", Code: []int{2788}},
	PLZ{Name: "Schleife", Code: []int{2959}},
	PLZ{Name: "Schlema", Code: []int{8301}},
	PLZ{Name: "Schlettau", Code: []int{9487}},
	PLZ{Name: "Schmiedeberg", Code: []int{1762}},
	PLZ{Name: "Schmolln-Putzkau", Code: []int{1877}},
	PLZ{Name: "Schneeberg", Code: []int{8289}},
	PLZ{Name: "Schonau-Berzdorf Auf Dem Eigen", Code: []int{2899}},
	PLZ{Name: "Schonbach", Code: []int{2708}},
	PLZ{Name: "Schonberg", Code: []int{8393}},
	PLZ{Name: "Schoneck/Vogtland", Code: []int{8261}},
	PLZ{Name: "Schonfeld", Code: []int{1561}},
	PLZ{Name: "Schonheide", Code: []int{8304}},
	PLZ{Name: "Schonteichen", Code: []int{1920}},
	PLZ{Name: "Schonwolkau", Code: []int{4509}},
	PLZ{Name: "Schopstal", Code: []int{2829}},
	PLZ{Name: "Schwarzenberg/Erzgebirge", Code: []int{8340}},
	PLZ{Name: "Schwepnitz", Code: []int{1936}},
	PLZ{Name: "Sebnitz", Code: []int{1855}},
	PLZ{Name: "Seelitz", Code: []int{9306}},
	PLZ{Name: "Sehmatal", Code: []int{9465}},
	PLZ{Name: "Seiffen/Erzgebirge", Code: []int{9548}},
	PLZ{Name: "Seifhennersdorf", Code: []int{2782}},
	PLZ{Name: "Sellerhausen-Stunz", Code: []int{4328}},
	PLZ{Name: "Siebenlehn", Code: []int{9634}},
	PLZ{Name: "Sohland Am Rotstein", Code: []int{2894}},
	PLZ{Name: "Sohland An Der Spree", Code: []int{2689}},
	PLZ{Name: "Sornzig-Ablas", Code: []int{4769}},
	PLZ{Name: "Sosa", Code: []int{8326}},
	PLZ{Name: "Spreetal", Code: []int{2979}},
	PLZ{Name: "Stadt Wehlen", Code: []int{1829}},
	PLZ{Name: "Stauchitz", Code: []int{1594}},
	PLZ{Name: "Steina", Code: []int{1920}},
	PLZ{Name: "Steinberg", Code: []int{8237}},
	PLZ{Name: "Steinigtwolmsdorf", Code: []int{1904}},
	PLZ{Name: "Steinpleis", Code: []int{8432}},
	PLZ{Name: "Stollberg/Erzgebirge", Code: []int{9366}},
	PLZ{Name: "Stolpen", Code: []int{1833}},
	PLZ{Name: "Strahwalde", Code: []int{2747}},
	PLZ{Name: "Strasgrabchen", Code: []int{1936}},
	PLZ{Name: "Strehla", Code: []int{1616}},
	PLZ{Name: "Striegistal", Code: []int{9661}},
	PLZ{Name: "Struppen", Code: []int{1796}},
	PLZ{Name: "Stutzengrun", Code: []int{8328}},
	PLZ{Name: "Syrau", Code: []int{8548}},
	PLZ{Name: "Tannenberg", Code: []int{9468}},
	PLZ{Name: "Tannenbergsthal/Vogtland", Code: []int{8262}},
	PLZ{Name: "Taubenheim", Code: []int{1665}},
	PLZ{Name: "Taucha", Code: []int{4425}},
	PLZ{Name: "Taura", Code: []int{9249}},
	PLZ{Name: "Tauscha", Code: []int{1561}},
	PLZ{Name: "Thalheim / Erzgebirge", Code: []int{9380}},
	PLZ{Name: "Thallwitz", Code: []int{4808}},
	PLZ{Name: "Tharandt", Code: []int{1737}},
	PLZ{Name: "Theuma", Code: []int{8541}},
	PLZ{Name: "Thiendorf", Code: []int{1561}},
	PLZ{Name: "Thum", Code: []int{9419}},
	PLZ{Name: "Thummlitzwalde", Code: []int{4668}},
	PLZ{Name: "Tiefenbach", Code: []int{9661}},
	PLZ{Name: "Tirpersdorf", Code: []int{8606}},
	PLZ{Name: "Torgau", Code: []int{4860}},
	PLZ{Name: "Trebendorf", Code: []int{2959}},
	PLZ{Name: "Trebsen/Mulde", Code: []int{4687}},
	PLZ{Name: "Treuen", Code: []int{8233}},
	PLZ{Name: "Triebel/Vogtland", Code: []int{8606}},
	PLZ{Name: "Triebischtal", Code: []int{1665}},
	PLZ{Name: "Trossin", Code: []int{4880}},
	PLZ{Name: "Uhyst", Code: []int{2999}},
	PLZ{Name: "Venusberg", Code: []int{9430}},
	PLZ{Name: "Vierkirchen", Code: []int{2894}},
	PLZ{Name: "Vogtlandisches Oberland", Code: []int{7952, 7985}},
	PLZ{Name: "Wachau", Code: []int{1454}},
	PLZ{Name: "Waldenburg", Code: []int{8396}},
	PLZ{Name: "Waldheim", Code: []int{4736}},
	PLZ{Name: "Waldhufen", Code: []int{2906}},
	PLZ{Name: "Waldkirchen/Erzgebirge", Code: []int{9437}},
	PLZ{Name: "Waltersdorf", Code: []int{2799}},
	PLZ{Name: "Wechselburg", Code: []int{9306}},
	PLZ{Name: "Weinbohla", Code: []int{1689}},
	PLZ{Name: "Weischlitz", Code: []int{8538}},
	PLZ{Name: "Weisenberg", Code: []int{2627}},
	PLZ{Name: "Weisenborn/Erzgebirge", Code: []int{9600}},
	PLZ{Name: "Weisig Am Raschutz", Code: []int{1561}},
	PLZ{Name: "Weiskeisel", Code: []int{2957}},
	PLZ{Name: "Weiswasser", Code: []int{2943}},
	PLZ{Name: "Weixdorf", Code: []int{1108}},
	PLZ{Name: "Werda", Code: []int{8223}},
	PLZ{Name: "Werdau", Code: []int{8412}},
	PLZ{Name: "Wermsdorf", Code: []int{4779}},
	PLZ{Name: "Wiedemar", Code: []int{4509}},
	PLZ{Name: "Wiednitz", Code: []int{2994}},
	PLZ{Name: "Wiesa", Code: []int{9488}},
	PLZ{Name: "Wildenfels", Code: []int{8134}},
	PLZ{Name: "Wildenfels Hartensdorf", Code: []int{8134}},
	PLZ{Name: "Wildenfels Schonau", Code: []int{8134}},
	PLZ{Name: "Wildenfels Wiesen", Code: []int{8134}},
	PLZ{Name: "Wildenfels Wiesenburg", Code: []int{8134}},
	PLZ{Name: "Wildenfels Wildenfels", Code: []int{8134}},
	PLZ{Name: "Wildenhain", Code: []int{1561}},
	PLZ{Name: "Wilkau-Haslau", Code: []int{8112}},
	PLZ{Name: "Wilschdorf", Code: []int{1109}},
	PLZ{Name: "Wilsdruff", Code: []int{1723}},
	PLZ{Name: "Wilthen", Code: []int{2681}},
	PLZ{Name: "Wittgensdorf", Code: []int{9228}},
	PLZ{Name: "Wittichenau", Code: []int{2997}},
	PLZ{Name: "Wolkenstein", Code: []int{9429}},
	PLZ{Name: "Wulknitz", Code: []int{1609}},
	PLZ{Name: "Wurzen", Code: []int{4808}},
	PLZ{Name: "Wyhratal", Code: []int{4552}},
	PLZ{Name: "Zabeltitz", Code: []int{1561}},
	PLZ{Name: "Zeithain", Code: []int{1619}},
	PLZ{Name: "Zettlitz", Code: []int{9306}},
	PLZ{Name: "Ziegra-Knobelsdorf", Code: []int{4720}},
	PLZ{Name: "Zinna", Code: []int{4860}},
	PLZ{Name: "Zittau", Code: []int{2763}},
	PLZ{Name: "Zoblitz", Code: []int{9517}},
	PLZ{Name: "Zschadras", Code: []int{4680}},
	PLZ{Name: "Zschaitz-Ottewig", Code: []int{4720}},
	PLZ{Name: "Zschepplin", Code: []int{4838}},
	PLZ{Name: "Zschopau", Code: []int{9405}},
	PLZ{Name: "Zschorlau", Code: []int{8321}},
	PLZ{Name: "Zschortau", Code: []int{4509}},
	PLZ{Name: "Zwenkau", Code: []int{4442}},
	PLZ{Name: "Zwickau", Code: []int{8056, 8058, 8060, 8062, 8064, 8066}},
	PLZ{Name: "Zwochau", Code: []int{4509}},
	PLZ{Name: "Zwonitz", Code: []int{8297}},
	PLZ{Name: "Zwota", Code: []int{8267}},
}
